<?php
$pageTitle='Cart | Moleqra';$pageRobots='noindex,nofollow';require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/commerce.php';$pdo=db();$error='';
if($pdo&&commerce_schema_ready($pdo)&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{
  $action=(string)($_POST['action']??'');$productId=(int)($_POST['product_id']??0);$variantId=(int)($_POST['variant_id']??0);$qty=(float)($_POST['quantity']??0);
  if($action==='add'){$p=commerce_product($pdo,$productId);$v=$p?commerce_variant($pdo,$p,$variantId):null;if(!$p||!$v||!$v['cart_enabled'])$error='This pack size is not available for cart ordering.';else{$add=max((float)$v['min_qty'],$qty);$target=commerce_cart_quantity($productId,(int)$v['id'])+$add;if($v['max_qty']!==null)$target=min($target,(float)$v['max_qty']);$target=min($target,commerce_variant_available_quantity($pdo,$productId,$v));if($target<=0)$error='No released stock is available.';else commerce_cart_set($productId,(int)$v['id'],$target);}}
  elseif($action==='update'){foreach((array)($_POST['qty']??[]) as $key=>$value){$ids=commerce_cart_parse_key((string)$key);commerce_cart_set($ids['product_id'],$ids['variant_id'],max(0,(float)$value));}}
  elseif($action==='remove')commerce_cart_set($productId,$variantId,0);
  if(!$error){header('Location: cart.php');exit;}
 }
}
$cart=$pdo&&commerce_schema_ready($pdo)?commerce_cart_details($pdo):['items'=>[],'subtotal'=>0,'tax'=>0,'shipping'=>0,'grand_total'=>0];require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><div class="eyebrow">Order</div><h1>Your cart</h1></div></section><section class="section"><div class="container"><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?><?php if(!$cart['items']):?><div class="card"><h2>Your cart is empty.</h2><a class="btn primary" href="catalog.php">Browse catalogue</a></div><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="update"><div class="table-wrap"><table class="data-table cart-table"><thead><tr><th>Product</th><th>Pack</th><th>Price</th><th>Qty</th><th>Total</th></tr></thead><tbody><?php foreach($cart['items'] as $item):$p=$item['product'];$v=$item['variant'];?><tr><td><a href="<?= e(storefront_product_path($p)) ?>"><?= e($p['sku'].' · '.$p['name']) ?></a></td><td><?= e($v['label']) ?><br><small><?= e($v['sku']) ?> · <?= e((string)$v['units_per_sale']) ?> base unit<?= (float)$v['units_per_sale']==1.0?'':'s' ?></small></td><td><?= commerce_money((float)$v['price']) ?></td><td><input class="cart-qty" type="number" name="qty[<?= e($item['key']) ?>]" min="0" step="<?= e((string)$v['min_qty']) ?>" value="<?= e((string)$item['quantity']) ?>"></td><td><?= commerce_money((float)$item['totals']['total']) ?></td></tr><?php endforeach;?></tbody></table></div><button class="btn" type="submit">Update cart</button></form><div class="checkout-summary card"><p><span>Items</span><strong><?= commerce_money($cart['subtotal']) ?></strong></p><?php if($cart['tax']>0):?><p><span>Tax component</span><strong><?= commerce_money($cart['tax']) ?></strong></p><?php endif;?><p><span>Estimated shipping</span><strong><?= $cart['shipping']>0?commerce_money($cart['shipping']):'Free' ?></strong></p><p class="checkout-total"><span>Estimated total</span><strong><?= commerce_money($cart['grand_total']) ?></strong></p><small class="muted">Shipping is recalculated from the delivery province during checkout.</small><a class="btn primary" href="checkout.php">Checkout</a></div><?php endif;?></div></section><?php require __DIR__.'/includes/footer.php';?>
