<?php
$pageTitle='Cart | Moleqra';require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/commerce.php';$pdo=db();$error='';
if($pdo&&commerce_schema_ready($pdo)&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{
  $action=(string)($_POST['action']??'');$productId=(int)($_POST['product_id']??0);$qty=(float)($_POST['quantity']??0);
  if($action==='add'){$p=commerce_product($pdo,$productId);if(!$p||!$p['cart_enabled'])$error='This product is not available for cart ordering.';else{$add=max((float)$p['min_qty'],$qty);$target=(float)(commerce_cart()[$productId]??0)+$add;if($p['max_qty']!==null)$target=min($target,(float)$p['max_qty']);$target=min($target,(float)$p['available_qty']);if($target<=0)$error='No released stock is available.';else commerce_cart_set($productId,$target);}}
  elseif($action==='update'){foreach((array)($_POST['qty']??[]) as $id=>$value)commerce_cart_set((int)$id,max(0,(float)$value));}
  elseif($action==='remove')commerce_cart_set($productId,0);
  if(!$error){header('Location: cart.php');exit;}
 }
}
$cart=$pdo&&commerce_schema_ready($pdo)?commerce_cart_details($pdo):['items'=>[],'subtotal'=>0,'tax'=>0,'shipping'=>0,'grand_total'=>0];require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><div class="eyebrow">Order</div><h1>Your cart</h1></div></section><section class="section"><div class="container"><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?><?php if(!$cart['items']):?><div class="card"><h2>Your cart is empty.</h2><a class="btn primary" href="catalog.php">Browse catalogue</a></div><?php else:?><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="update"><div class="table-wrap"><table class="data-table cart-table"><thead><tr><th>Product</th><th>Price</th><th>Qty</th><th>Total</th></tr></thead><tbody><?php foreach($cart['items'] as $item):$p=$item['product'];?><tr><td><a href="product.php?id=<?= (int)$p['id'] ?>"><?= e($p['sku'].' · '.$p['name']) ?></a><br><small><?= e((string)$p['available_qty']) ?> available</small></td><td><?= commerce_money((float)$p['price']) ?></td><td><input class="cart-qty" type="number" name="qty[<?= (int)$p['id'] ?>]" min="0" step="<?= e((string)$p['min_qty']) ?>" value="<?= e((string)$item['quantity']) ?>"></td><td><?= commerce_money((float)$item['totals']['total']) ?></td></tr><?php endforeach;?></tbody></table></div><button class="btn" type="submit">Update cart</button></form><div class="checkout-summary card"><p><span>Items</span><strong><?= commerce_money($cart['subtotal']) ?></strong></p><?php if($cart['tax']>0):?><p><span>Tax included/calculated</span><strong><?= commerce_money($cart['tax']) ?></strong></p><?php endif;?><p><span>Shipping</span><strong><?= $cart['shipping']>0?commerce_money($cart['shipping']):'Free' ?></strong></p><p class="checkout-total"><span>Total</span><strong><?= commerce_money($cart['grand_total']) ?></strong></p><a class="btn primary" href="checkout.php">Checkout</a></div><?php endif;?></div></section><?php require __DIR__.'/includes/footer.php';?>
