<?php
$pageTitle='Product | Moleqra';
require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/commerce.php';
$pdo=db();$id=(int)($_GET['id']??0);$product=$pdo&&commerce_schema_ready($pdo)?commerce_product($pdo,$id):null;if(!$product){http_response_code(404);$pageTitle='Product unavailable | Moleqra';}
if($product)$pageTitle=$product['name'].' | Moleqra';
require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><div class="eyebrow">Research material</div><h1><?= e($product['name']??'Product unavailable') ?></h1><?php if($product): ?><p><?= e($product['description']?:$product['format']) ?></p><?php endif; ?></div></section>
<section class="section"><div class="container"><?php if(!$product): ?><div class="card"><h2>Not available</h2><p>This product is not currently available for public ordering.</p><a class="btn" href="catalog.php">Back to catalogue</a></div><?php else: ?><div class="grid-2"><article class="card"><span class="sku"><?= e($product['sku']) ?></span><h2><?= e($product['name']) ?></h2><p><?= e($product['format']) ?></p><dl class="product-meta"><div><dt>Status</dt><dd><?= e($product['status']) ?></dd></div><?php if($product['purity_label']): ?><div><dt>Reported purity</dt><dd><?= e($product['purity_label']) ?></dd></div><?php endif; ?><div><dt>Available</dt><dd><?= e((string)$product['available_qty']) ?> <?= e($product['sale_unit_label']) ?>(s)</dd></div></dl><div class="notice"><strong>Research use only.</strong> Not for human or veterinary use. Moleqra does not provide dosing or administration guidance.</div></article><aside class="card"><div class="price-line"><strong><?= commerce_money((float)$product['price']) ?></strong><span>per <?= e($product['sale_unit_label']) ?></span></div><?php if((float)$product['available_qty']>0 && $product['cart_enabled']): ?><form method="post" action="cart.php"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add"><input type="hidden" name="product_id" value="<?= (int)$product['id'] ?>"><div class="field"><label>Quantity</label><input type="number" name="quantity" min="<?= e((string)$product['min_qty']) ?>"<?= $product['max_qty']!==null?' max="'.e((string)min((float)$product['max_qty'],(float)$product['available_qty'])).'"':'' ?> step="<?= e((string)$product['min_qty']) ?>" value="<?= e((string)$product['min_qty']) ?>"></div><button class="btn primary" type="submit">Add to cart</button></form><?php else: ?><div class="alert error">No released inventory is currently available for online ordering.</div><?php endif; ?></aside></div><?php endif; ?></div></section>
<?php require __DIR__.'/includes/footer.php'; ?>
