<?php
$pageTitle='Product | Moleqra';require_once __DIR__.'/includes/bootstrap.php';require_once __DIR__.'/includes/commerce.php';require_once __DIR__.'/includes/seo.php';
$pdo=db();$id=(int)($_GET['id']??0);$slug=trim((string)($_GET['slug']??''));$product=null;
if($pdo&&commerce_schema_ready($pdo)){$product=$slug!==''&&function_exists('storefront_product_by_slug')?storefront_product_by_slug($pdo,$slug):commerce_product($pdo,$id);}
if(!$product){http_response_code(404);$pageTitle='Product unavailable | Moleqra';$pageRobots='noindex,follow';}
$related=[];$offers=[];
if($product){$pageTitle=($product['meta_title']??'')?:$product['name'].' | Moleqra';$pageDescription=($product['meta_description']??'')?:storefront_summary($product);$canonicalUrl=seo_product_url($product);if(isset($product['seo_indexable'])&&!$product['seo_indexable'])$pageRobots='noindex,follow';
    $variants=$product['variants']?:[];if(!$variants){$fallback=commerce_variant($pdo,$product,0);if($fallback)$variants=[$fallback];}
    foreach($variants as &$variant){$variant['available_qty']=commerce_variant_available_quantity($pdo,(int)$product['id'],$variant);$offer=seo_offer_schema($variant,(float)$variant['available_qty']);if($canonicalUrl!=='')$offer['url']=$canonicalUrl;$offers[]=$offer;}unset($variant);
    $structuredData=[seo_product_schema($product,$offers)];$related=function_exists('storefront_related_products')?storefront_related_products($pdo,(int)$product['id'],4):[];
}
require __DIR__.'/includes/header.php';
?>
<section class="page-hero"><div class="container"><div class="eyebrow"><?= e($product['category']??'Research material') ?></div><h1><?= e($product['name']??'Product unavailable') ?></h1><?php if($product):?><p><?= e(storefront_summary($product)) ?></p><?php endif;?></div></section>
<section class="section"><div class="container"><?php if(!$product):?><div class="card"><h2>Not available</h2><p>This product is not currently available for public ordering.</p><a class="btn" href="catalog.php">Back to catalogue</a></div><?php else:?><div class="grid-2 product-detail-grid"><article class="card"><span class="sku"><?= e($product['sku']) ?></span><h2><?= e($product['name']) ?></h2><p><?= e($product['format']) ?></p><dl class="product-meta"><div><dt>Status</dt><dd><?= e($product['status']) ?></dd></div><?php if($product['purity_label']):?><div><dt>Reported purity</dt><dd><?= e($product['purity_label']) ?></dd></div><?php endif;?><div><dt>Stock</dt><dd><?= e(storefront_stock_message($product)) ?></dd></div></dl><div class="notice"><strong>Research use only.</strong> Not for human or veterinary use. Moleqra does not provide dosing or administration guidance.</div></article>
<aside class="card"><h2>Pack sizes</h2><?php if($variants):?><div class="variant-list"><?php foreach($variants as $variant):?><section class="variant-option"><div><strong><?= e($variant['label']) ?></strong><span class="muted small"><?= e($variant['sku']) ?> · <?= e((string)$variant['units_per_sale']) ?> stock unit<?= (float)$variant['units_per_sale']==1.0?'':'s' ?> per <?= e($variant['sale_unit_label']) ?></span></div><div class="variant-price"><strong><?= commerce_money((float)$variant['price']) ?></strong><span class="stock-status <?= (float)$variant['available_qty']<=0?'out':'' ?>"><?= (float)$variant['available_qty']>0?'Available':'Out of stock' ?></span></div><?php if((float)$variant['available_qty']>0&&!empty($variant['cart_enabled'])):?><form method="post" action="cart.php" class="variant-cart-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add"><input type="hidden" name="product_id" value="<?= (int)$product['id'] ?>"><input type="hidden" name="variant_id" value="<?= (int)$variant['id'] ?>"><div class="field"><label>Quantity</label><input type="number" name="quantity" min="<?= e((string)$variant['min_qty']) ?>"<?= $variant['max_qty']!==null?' max="'.e((string)$variant['max_qty']).'"':'' ?> step="<?= e((string)$variant['min_qty']) ?>" value="<?= e((string)$variant['min_qty']) ?>"></div><button class="btn primary">Add to cart</button></form><?php endif;?></section><?php endforeach;?></div><?php else:?><div class="alert error">No sellable pack sizes are currently configured.</div><?php endif;?></aside></div>
<?php if($related):?><section class="related-section"><div class="section-head"><div><div class="eyebrow">Related materials</div><h2>Explore the catalogue</h2></div></div><div class="product-grid"><?php foreach($related as $rp):$rpPath=storefront_product_path($rp);?><article class="product-card"><span class="sku"><?= e($rp['sku']) ?></span><h3><a href="<?= e($rpPath) ?>"><?= e($rp['name']) ?></a></h3><p><?= e(storefront_summary($rp)) ?></p><div class="product-footer"><span><?= commerce_money((float)$rp['price']) ?></span><a href="<?= e($rpPath) ?>">View →</a></div></article><?php endforeach;?></div></section><?php endif;?>
<?php endif;?></div></section>
<?php require __DIR__.'/includes/footer.php';?>
