<?php
$rootPrefix='../';$pageTitle='Saved addresses | Moleqra';require_once __DIR__.'/../includes/bootstrap.php';require_once __DIR__.'/../includes/account_auth.php';require_once __DIR__.'/../includes/customer_addresses.php';
$user=customer_user();if(!$user){header('Location: login.php');exit;}$pdo=db();$error='';$editId=(int)($_GET['edit']??$_POST['address_id']??0);
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{try{$action=(string)($_POST['action']??'save');if($action==='delete'){customer_delete_address($pdo,(int)$user['id'],$editId);header('Location: addresses.php?deleted=1');exit;}$data=$_POST;$data['is_default']=isset($_POST['is_default']);customer_save_address($pdo,(int)$user['id'],$data,$editId?:null);header('Location: addresses.php?saved=1');exit;}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'The address could not be saved.';}}
}
$addresses=customer_addresses($pdo,(int)$user['id']);$editing=null;if($editId){foreach($addresses as $a)if((int)$a['id']===$editId)$editing=$a;}
require __DIR__.'/../includes/header.php';
?>
<section class="page-hero"><div class="container"><div class="eyebrow">Customer account</div><h1>Saved addresses</h1><p>Manage delivery addresses used to prefill checkout.</p></div></section>
<section class="section"><div class="container">
<?php if(isset($_GET['saved'])):?><div class="alert success">Address saved.</div><?php endif;?><?php if(isset($_GET['deleted'])):?><div class="alert success">Address deleted.</div><?php endif;?><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?>
<div class="grid-2"><section class="card"><h2><?= $editing?'Edit address':'Add address' ?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save"><input type="hidden" name="address_id" value="<?= (int)($editing['id']??0) ?>"><div class="form-grid">
<div class="field"><label>Label</label><input name="label" value="<?= e($editing['label']??'Default') ?>"></div><div class="field"><label>Recipient</label><input name="recipient_name" required value="<?= e($editing['recipient_name']??($user['first_name'].' '.$user['last_name'])) ?>"></div>
<div class="field full"><label>Company</label><input name="company" value="<?= e($editing['company']??$user['company']??'') ?>"></div><div class="field full"><label>Address</label><input name="address_line1" required value="<?= e($editing['address_line1']??'') ?>"></div><div class="field full"><label>Address line 2</label><input name="address_line2" value="<?= e($editing['address_line2']??'') ?>"></div>
<div class="field"><label>City</label><input name="city" required value="<?= e($editing['city']??'') ?>"></div><div class="field"><label>Province</label><input name="province" required value="<?= e($editing['province']??'') ?>"></div><div class="field"><label>Postal code</label><input name="postal_code" required value="<?= e($editing['postal_code']??'') ?>"></div><div class="field"><label>Country</label><input name="country_code" maxlength="2" value="<?= e($editing['country_code']??'ZA') ?>"></div><div class="field full"><label>Phone</label><input name="phone" value="<?= e($editing['phone']??$user['phone']??'') ?>"></div></div><label class="checkout-save-address"><input type="checkbox" name="is_default" value="1"<?= !isset($editing['is_default'])||!empty($editing['is_default'])?' checked':'' ?>> Use as default address</label><button class="btn primary">Save address</button><?php if($editing):?> <a class="btn" href="addresses.php">Cancel</a><?php endif;?></form></section>
<section class="card"><h2>Your addresses</h2><div class="address-list"><?php foreach($addresses as $a):?><article class="saved-address"><div><strong><?= e($a['label']) ?><?= $a['is_default']?' · Default':'' ?></strong><p><?= e($a['recipient_name']) ?><br><?= e($a['address_line1']) ?><?= $a['address_line2']?'<br>'.e($a['address_line2']):'' ?><br><?= e($a['city'].', '.$a['province'].' '.$a['postal_code']) ?></p></div><div class="address-actions"><a href="addresses.php?edit=<?= (int)$a['id'] ?>">Edit</a><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="address_id" value="<?= (int)$a['id'] ?>"><button class="link-button" type="submit">Delete</button></form></div></article><?php endforeach;?><?php if(!$addresses):?><p class="muted">No saved addresses yet.</p><?php endif;?></div></section></div>
<p><a href="index.php">← Back to account</a></p></div></section>
<?php require __DIR__.'/../includes/footer.php';?>
