CREATE TABLE IF NOT EXISTS customer_accounts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(180) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  company VARCHAR(160) NULL,
  phone VARCHAR(60) NULL,
  is_active TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_login_at DATETIME NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_customer_accounts_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS customer_addresses (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  customer_id BIGINT UNSIGNED NOT NULL,
  label VARCHAR(60) NOT NULL DEFAULT 'Default',
  recipient_name VARCHAR(180) NOT NULL,
  company VARCHAR(160) NULL,
  address_line1 VARCHAR(180) NOT NULL,
  address_line2 VARCHAR(180) NULL,
  city VARCHAR(120) NOT NULL,
  province VARCHAR(120) NOT NULL,
  postal_code VARCHAR(30) NOT NULL,
  country_code CHAR(2) NOT NULL DEFAULT 'ZA',
  phone VARCHAR(60) NULL,
  is_default TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_customer_addresses_customer (customer_id,is_default),
  CONSTRAINT fk_customer_addresses_customer FOREIGN KEY (customer_id) REFERENCES customer_accounts(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_commerce (
  product_id BIGINT UNSIGNED NOT NULL,
  price DECIMAL(14,2) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'ZAR',
  tax_rate DECIMAL(6,3) NOT NULL DEFAULT 0,
  tax_inclusive TINYINT(1) NOT NULL DEFAULT 1,
  cart_enabled TINYINT(1) NOT NULL DEFAULT 0,
  min_qty DECIMAL(12,3) NOT NULL DEFAULT 1,
  max_qty DECIMAL(12,3) NULL,
  sale_unit_label VARCHAR(60) NOT NULL DEFAULT 'unit',
  shipping_class VARCHAR(60) NOT NULL DEFAULT 'standard',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (product_id),
  CONSTRAINT fk_product_commerce_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_number VARCHAR(40) NOT NULL,
  order_token CHAR(64) NOT NULL,
  customer_id BIGINT UNSIGNED NULL,
  status VARCHAR(40) NOT NULL DEFAULT 'Pending payment',
  payment_status VARCHAR(40) NOT NULL DEFAULT 'Pending',
  fulfilment_status VARCHAR(40) NOT NULL DEFAULT 'Unfulfilled',
  currency CHAR(3) NOT NULL DEFAULT 'ZAR',
  subtotal DECIMAL(14,2) NOT NULL,
  shipping_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  grand_total DECIMAL(14,2) NOT NULL,
  email VARCHAR(180) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  company VARCHAR(160) NULL,
  phone VARCHAR(60) NULL,
  address_line1 VARCHAR(180) NOT NULL,
  address_line2 VARCHAR(180) NULL,
  city VARCHAR(120) NOT NULL,
  province VARCHAR(120) NOT NULL,
  postal_code VARCHAR(30) NOT NULL,
  country_code CHAR(2) NOT NULL DEFAULT 'ZA',
  payment_method VARCHAR(40) NOT NULL DEFAULT 'payfast',
  ruo_acknowledged_at DATETIME NOT NULL,
  terms_accepted_at DATETIME NOT NULL,
  paid_at DATETIME NULL,
  cancelled_at DATETIME NULL,
  customer_note TEXT NULL,
  admin_note TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_sales_orders_number (order_number),
  UNIQUE KEY uq_sales_orders_token (order_token),
  INDEX idx_sales_orders_customer (customer_id,created_at),
  INDEX idx_sales_orders_status (status,payment_status,fulfilment_status),
  CONSTRAINT fk_sales_orders_customer FOREIGN KEY (customer_id) REFERENCES customer_accounts(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sales_order_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  sku VARCHAR(50) NOT NULL,
  product_name VARCHAR(120) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit_price DECIMAL(14,2) NOT NULL,
  tax_rate DECIMAL(6,3) NOT NULL DEFAULT 0,
  tax_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
  line_total DECIMAL(14,2) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_sales_order_items_order (order_id),
  INDEX idx_sales_order_items_product (product_id),
  CONSTRAINT fk_sales_order_items_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_sales_order_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stock_reservations (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  order_item_id BIGINT UNSIGNED NOT NULL,
  batch_id BIGINT UNSIGNED NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'Active',
  expires_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_stock_reservations_batch (batch_id,status,expires_at),
  INDEX idx_stock_reservations_order (order_id,status),
  CONSTRAINT fk_stock_reservations_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_stock_reservations_item FOREIGN KEY (order_item_id) REFERENCES sales_order_items(id) ON DELETE CASCADE,
  CONSTRAINT fk_stock_reservations_batch FOREIGN KEY (batch_id) REFERENCES inventory_batches(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS payment_transactions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  gateway VARCHAR(40) NOT NULL,
  gateway_payment_id VARCHAR(120) NULL,
  gateway_status VARCHAR(60) NULL,
  amount_gross DECIMAL(14,2) NULL,
  amount_fee DECIMAL(14,2) NULL,
  amount_net DECIMAL(14,2) NULL,
  signature_valid TINYINT(1) NOT NULL DEFAULT 0,
  source_valid TINYINT(1) NOT NULL DEFAULT 0,
  amount_valid TINYINT(1) NOT NULL DEFAULT 0,
  server_valid TINYINT(1) NOT NULL DEFAULT 0,
  payload MEDIUMTEXT NULL,
  received_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_payment_gateway_id (gateway,gateway_payment_id),
  INDEX idx_payment_transactions_order (order_id,received_at),
  CONSTRAINT fk_payment_transactions_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS order_shipments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  order_id BIGINT UNSIGNED NOT NULL,
  courier VARCHAR(100) NULL,
  service VARCHAR(100) NULL,
  tracking_number VARCHAR(160) NULL,
  dispatched_at DATETIME NULL,
  delivered_at DATETIME NULL,
  notes TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_order_shipments_order (order_id),
  CONSTRAINT fk_order_shipments_order FOREIGN KEY (order_id) REFERENCES sales_orders(id) ON DELETE CASCADE,
  CONSTRAINT fk_order_shipments_admin FOREIGN KEY (created_by) REFERENCES admin_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
