CREATE TABLE IF NOT EXISTS communication_threads (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  party_type VARCHAR(30) NOT NULL DEFAULT 'contact',
  customer_id BIGINT UNSIGNED NULL,
  supplier_id BIGINT UNSIGNED NULL,
  enquiry_id BIGINT UNSIGNED NULL,
  contact_name VARCHAR(160) NULL,
  email VARCHAR(180) NOT NULL,
  subject VARCHAR(220) NOT NULL,
  source VARCHAR(40) NOT NULL DEFAULT 'Manual',
  status VARCHAR(24) NOT NULL DEFAULT 'Open',
  assigned_to BIGINT UNSIGNED NULL,
  last_message_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_communication_thread_enquiry (enquiry_id),
  INDEX idx_communication_threads_customer (customer_id,last_message_at),
  INDEX idx_communication_threads_supplier (supplier_id,last_message_at),
  INDEX idx_communication_threads_email (email,last_message_at),
  INDEX idx_communication_threads_status (status,last_message_at),
  CONSTRAINT fk_communication_thread_customer FOREIGN KEY (customer_id) REFERENCES customer_accounts(id) ON DELETE SET NULL,
  CONSTRAINT fk_communication_thread_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
  CONSTRAINT fk_communication_thread_enquiry FOREIGN KEY (enquiry_id) REFERENCES enquiries(id) ON DELETE SET NULL,
  CONSTRAINT fk_communication_thread_admin FOREIGN KEY (assigned_to) REFERENCES admin_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS communication_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  thread_id BIGINT UNSIGNED NOT NULL,
  direction VARCHAR(16) NOT NULL,
  channel VARCHAR(24) NOT NULL DEFAULT 'Email',
  sender_email VARCHAR(180) NULL,
  recipient_email VARCHAR(180) NULL,
  subject VARCHAR(220) NULL,
  body_text MEDIUMTEXT NULL,
  body_html MEDIUMTEXT NULL,
  transport VARCHAR(30) NULL,
  status VARCHAR(24) NOT NULL DEFAULT 'Received',
  external_message_id VARCHAR(255) NULL,
  in_reply_to VARCHAR(255) NULL,
  sent_by_admin BIGINT UNSIGNED NULL,
  error_message TEXT NULL,
  sent_at DATETIME NULL,
  received_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_communication_external_message (external_message_id),
  INDEX idx_communication_messages_thread (thread_id,created_at),
  INDEX idx_communication_messages_direction (direction,created_at),
  INDEX idx_communication_messages_sender (sender_email,created_at),
  CONSTRAINT fk_communication_message_thread FOREIGN KEY (thread_id) REFERENCES communication_threads(id) ON DELETE CASCADE,
  CONSTRAINT fk_communication_message_admin FOREIGN KEY (sent_by_admin) REFERENCES admin_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
