CREATE TABLE IF NOT EXISTS supplier_qualifications (
  supplier_id BIGINT UNSIGNED NOT NULL,
  business_verified TINYINT(1) NOT NULL DEFAULT 0,
  sample_coa_received TINYINT(1) NOT NULL DEFAULT 0,
  batch_specific_coa TINYINT(1) NOT NULL DEFAULT 0,
  hplc_present TINYINT(1) NOT NULL DEFAULT 0,
  mass_spec_present TINYINT(1) NOT NULL DEFAULT 0,
  coa_identity_matches TINYINT(1) NOT NULL DEFAULT 0,
  ruo_label_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  private_label_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  shipping_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  payment_terms_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  returns_process_confirmed TINYINT(1) NOT NULL DEFAULT 0,
  qualification_notes TEXT NULL,
  reviewed_at DATE NULL,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (supplier_id),
  CONSTRAINT fk_supplier_qualifications_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_products (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  supplier_id BIGINT UNSIGNED NOT NULL,
  product_id BIGINT UNSIGNED NOT NULL,
  supplier_sku VARCHAR(100) NULL,
  availability VARCHAR(40) NOT NULL DEFAULT 'Unknown',
  wholesale_price DECIMAL(12,2) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'ZAR',
  moq_units INT UNSIGNED NULL,
  moq_value DECIMAL(12,2) NULL,
  lead_time_days INT UNSIGNED NULL,
  coa_available TINYINT(1) NOT NULL DEFAULT 0,
  private_label TINYINT(1) NOT NULL DEFAULT 0,
  dropship TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_supplier_products_pair (supplier_id, product_id),
  INDEX idx_supplier_products_product (product_id),
  CONSTRAINT fk_supplier_products_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_products_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_outreach (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  supplier_id BIGINT UNSIGNED NOT NULL,
  contacted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  channel VARCHAR(30) NOT NULL DEFAULT 'Email',
  subject VARCHAR(180) NULL,
  notes TEXT NOT NULL,
  outcome VARCHAR(40) NOT NULL DEFAULT 'Awaiting response',
  next_follow_up DATE NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_supplier_outreach_supplier (supplier_id, contacted_at),
  INDEX idx_supplier_outreach_followup (next_follow_up, outcome),
  CONSTRAINT fk_supplier_outreach_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
  CONSTRAINT fk_supplier_outreach_admin FOREIGN KEY (created_by) REFERENCES admin_users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS supplier_test_orders (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  supplier_id BIGINT UNSIGNED NOT NULL,
  order_ref VARCHAR(100) NULL,
  ordered_at DATE NOT NULL,
  received_at DATE NULL,
  amount DECIMAL(12,2) NULL,
  currency CHAR(3) NOT NULL DEFAULT 'ZAR',
  status VARCHAR(40) NOT NULL DEFAULT 'Planned',
  courier VARCHAR(100) NULL,
  tracking_ref VARCHAR(160) NULL,
  packaging_condition TINYINT UNSIGNED NULL,
  documentation_complete TINYINT(1) NOT NULL DEFAULT 0,
  batch_matches_coa TINYINT(1) NOT NULL DEFAULT 0,
  notes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_supplier_test_orders_supplier (supplier_id, ordered_at),
  INDEX idx_supplier_test_orders_status (status),
  CONSTRAINT fk_supplier_test_orders_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE CASCADE,
  CONSTRAINT chk_supplier_test_orders_packaging CHECK (packaging_condition IS NULL OR packaging_condition BETWEEN 1 AND 5)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
