<?php
$adminTitle='Community';require __DIR__.'/_header.php';require_once __DIR__.'/../includes/community.php';require_once __DIR__.'/../includes/audit.php';
$pdo=db();$ready=$pdo&&community_schema_ready($pdo);$error='';$message='';
if($ready&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';
 else{try{$action=(string)($_POST['action']??'');$adminId=(int)(admin_user()['id']??0)?:null;
   if($action==='post_status'){$id=(int)($_POST['post_id']??0);$status=(string)($_POST['status']??'Hidden');if(!in_array($status,['Published','Hidden'],true))throw new RuntimeException('Invalid post status.');$reason=trim((string)($_POST['reason']??''));$pdo->prepare("UPDATE forum_posts SET status=:status,hidden_reason=:reason WHERE id=:id")->execute(['status'=>$status,'reason'=>$status==='Hidden'?($reason?:'Moderated by administrator'):null,'id'=>$id]);admin_audit($pdo,'forum.post_status','forum_post',(string)$id,'Changed forum post status',['status'=>$status]);$message='Post updated.';}
   elseif($action==='topic_status'){$id=(int)($_POST['topic_id']??0);$status=(string)($_POST['status']??'Closed');if(!in_array($status,['Open','Closed','Hidden'],true))throw new RuntimeException('Invalid topic state.');$pdo->prepare('UPDATE forum_topics SET status=:status WHERE id=:id')->execute(['status'=>$status,'id'=>$id]);admin_audit($pdo,'forum.topic_status','forum_topic',(string)$id,'Changed forum topic status',['status'=>$status]);$message='Topic updated.';}
   elseif($action==='customer_status'){$id=(int)($_POST['customer_id']??0);$status=(string)($_POST['status']??'Blocked');if(!in_array($status,['Active','Suspended','Blocked'],true))throw new RuntimeException('Invalid forum account state.');$reason=trim((string)($_POST['reason']??''));$pdo->prepare("INSERT INTO forum_customer_moderation(customer_id,forum_status,block_reason,blocked_at,blocked_by) VALUES(:id,:status,:reason,IF(:status='Active',NULL,NOW()),:admin) ON DUPLICATE KEY UPDATE forum_status=VALUES(forum_status),block_reason=VALUES(block_reason),blocked_at=VALUES(blocked_at),blocked_by=VALUES(blocked_by),spam_score=IF(VALUES(forum_status)='Active',0,spam_score)")->execute(['id'=>$id,'status'=>$status,'reason'=>$status==='Active'?null:($reason?:'Administrative moderation'),'admin'=>$status==='Active'?null:$adminId]);admin_audit($pdo,'forum.customer_status','customer',(string)$id,'Changed community access',['status'=>$status,'reason'=>$reason]);$message='Customer community access updated.';}
 }catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'Community moderation failed.';}}
}
$topics=$ready?$pdo->query("SELECT t.*,p.name product_name,(SELECT COUNT(*) FROM forum_posts fp WHERE fp.topic_id=t.id) post_count FROM forum_topics t LEFT JOIN products p ON p.id=t.product_id ORDER BY COALESCE(t.last_post_at,t.created_at) DESC LIMIT 200")->fetchAll():[];
$posts=$ready?$pdo->query("SELECT fp.*,t.title topic_title,ca.email,COALESCE(m.forum_status,'Active') forum_status,COALESCE(m.spam_score,0) spam_score FROM forum_posts fp JOIN forum_topics t ON t.id=fp.topic_id JOIN customer_accounts ca ON ca.id=fp.customer_id LEFT JOIN forum_customer_moderation m ON m.customer_id=fp.customer_id ORDER BY fp.created_at DESC LIMIT 300")->fetchAll():[];
?>
<div class="admin-heading"><div><div class="eyebrow">Moderation</div><h1>Community</h1><p class="muted">Moderate posts/topics and restrict forum access without disabling customer ordering accounts.</p></div></div>
<?php if($message):?><div class="alert success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$ready):?><div class="alert error">Migration 010 is not installed.</div><?php else:?>
<section class="card"><h2>Topics</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Topic</th><th>Type</th><th>Status</th><th>Posts</th><th>Moderate</th></tr></thead><tbody><?php foreach($topics as $t):?><tr><td><strong><?=e($t['title'])?></strong><br><small><?=e($t['created_at'])?></small></td><td><?= $t['is_product_topic']?'Product · '.e($t['product_name']):'Custom' ?></td><td><?=e($t['status'])?></td><td><?=(int)$t['post_count']?></td><td><form method="post" class="inline-select"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="topic_status"><input type="hidden" name="topic_id" value="<?=(int)$t['id']?>"><select name="status"><option<?= $t['status']==='Open'?' selected':'' ?>>Open</option><option<?= $t['status']==='Closed'?' selected':'' ?>>Closed</option><option<?= $t['status']==='Hidden'?' selected':'' ?>>Hidden</option></select><button class="btn">Save</button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="card admin-section-gap"><h2>Recent posts</h2><?php foreach($posts as $p):?><article class="moderation-post"><div class="section-heading"><div><strong><?=e($p['topic_title'])?></strong><p class="muted"><?=e(community_member_label((int)$p['customer_id']))?> · <?=e($p['email'])?> · <?=e($p['created_at'])?> · spam score <?=(int)$p['spam_score']?></p></div><span class="status-pill"><?=e($p['status'])?></span></div><p><?=nl2br(e($p['body']))?></p><div class="admin-actions"><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="post_status"><input type="hidden" name="post_id" value="<?=(int)$p['id']?>"><input type="hidden" name="status" value="<?= $p['status']==='Published'?'Hidden':'Published' ?>"><input name="reason" placeholder="Moderation reason (optional)"><button class="btn"><?= $p['status']==='Published'?'Hide post':'Restore post' ?></button></form><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="customer_status"><input type="hidden" name="customer_id" value="<?=(int)$p['customer_id']?>"><select name="status"><option>Active</option><option>Suspended</option><option>Blocked</option></select><input name="reason" placeholder="Reason"><button class="btn">Update customer access</button></form></div></article><?php endforeach;?></section>
<?php endif;?>
<?php require __DIR__.'/_footer.php';?>
