<?php
$adminTitle='Commerce';require __DIR__.'/_header.php';require_once __DIR__.'/../includes/commerce.php';require_once __DIR__.'/../includes/payments.php';require_once __DIR__.'/../includes/storefront.php';$pdo=db();$ready=commerce_schema_ready($pdo);$error='';
if($pdo&&$ready&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{try{$productId=(int)($_POST['product_id']??0);$price=trim((string)($_POST['price']??''));$currency=strtoupper(trim((string)($_POST['currency']??commerce_currency())));$tax=max(0,(float)($_POST['tax_rate']??0));$min=max(.001,(float)($_POST['min_qty']??1));$max=trim((string)($_POST['max_qty']??''));$label=trim((string)($_POST['sale_unit_label']??'unit'))?:'unit';if($productId<1)throw new RuntimeException('Choose a product.');$sql='INSERT INTO product_commerce(product_id,price,currency,tax_rate,tax_inclusive,cart_enabled,min_qty,max_qty,sale_unit_label,shipping_class) VALUES(:product,:price,:currency,:tax,:inclusive,:enabled,:min,:max,:label,:shipping) ON DUPLICATE KEY UPDATE price=VALUES(price),currency=VALUES(currency),tax_rate=VALUES(tax_rate),tax_inclusive=VALUES(tax_inclusive),cart_enabled=VALUES(cart_enabled),min_qty=VALUES(min_qty),max_qty=VALUES(max_qty),sale_unit_label=VALUES(sale_unit_label),shipping_class=VALUES(shipping_class)';$pdo->prepare($sql)->execute(['product'=>$productId,'price'=>$price===''?null:max(0,(float)$price),'currency'=>$currency,'tax'=>$tax,'inclusive'=>isset($_POST['tax_inclusive'])?1:0,'enabled'=>isset($_POST['cart_enabled'])?1:0,'min'=>$min,'max'=>$max===''?null:max($min,(float)$max),'label'=>$label,'shipping'=>trim((string)($_POST['shipping_class']??'standard'))?:'standard']);admin_audit($pdo,'commerce.base.save','product',(string)$productId,'Updated base commerce offer');header('Location: commerce.php?saved=1');exit;}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'Commerce settings could not be saved.';}}
}
$rows=$ready?$pdo->query('SELECT p.id,p.sku,p.name,p.is_public,pc.* FROM products p LEFT JOIN product_commerce pc ON pc.product_id=p.id ORDER BY p.sort_order,p.name')->fetchAll():[];
?>
<div class="admin-heading"><div><div class="eyebrow">Storefront</div><h1>Commerce</h1></div><div class="admin-actions"><a class="btn" href="storefront.php">Pack sizes &amp; SEO</a><a class="btn" href="orders.php">Orders</a></div></div><?php if(!$ready):?><div class="alert error">V6 commerce is not installed. <a href="system.php">Run the V6 upgrade</a>.</div><?php endif;?><?php if(isset($_GET['saved'])):?><div class="alert success">Commerce settings saved.</div><?php endif;?><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?>
<?php if($ready):?><section class="card"><div class="section-heading"><div><h2>Payment readiness</h2><p class="muted">Hosted PayFast integration is <?= payfast_configured()?'configured':'not configured' ?> and currently set to <?= payfast_sandbox()?'sandbox':'live' ?> mode.</p></div><span class="status-pill <?= payfast_configured()?'status-qualified':'' ?>"><?= payfast_configured()?'Configured':'Config required' ?></span></div><p class="muted">Copy <code>config/payment.example.php</code> to <code>config/payment.php</code>, enter the merchant credentials/passphrase, and set <code>base_url</code> in <code>config/app.php</code>. Keep sandbox enabled until ITN tests pass.</p></section>
<section class="card admin-section-gap"><h2>Base product commerce settings</h2><p class="muted">These remain the fallback offer when a product has no V8 pack variants. Once variants exist, public product pages use their variant prices and pack quantities.</p><div class="commerce-product-list"><?php foreach($rows as $r):?><details class="commerce-product"><summary><strong><?= e($r['sku'].' · '.$r['name']) ?></strong><span><?= $r['cart_enabled']?'Cart enabled':'Disabled' ?> · <?= $r['price']!==null?e(($r['currency']?:commerce_currency()).' '.number_format((float)$r['price'],2)):'No price' ?></span></summary><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="product_id" value="<?= (int)$r['id'] ?>"><div class="field"><label>Price</label><input type="number" min="0" step="0.01" name="price" value="<?= e((string)($r['price']??'')) ?>"></div><div class="field"><label>Currency</label><input name="currency" maxlength="3" value="<?= e($r['currency']?:commerce_currency()) ?>"></div><div class="field"><label>Tax rate %</label><input type="number" min="0" step="0.001" name="tax_rate" value="<?= e((string)($r['tax_rate']??0)) ?>"></div><div class="field"><label>Unit label</label><input name="sale_unit_label" value="<?= e($r['sale_unit_label']?:'unit') ?>"></div><div class="field"><label>Minimum qty</label><input type="number" min="0.001" step="0.001" name="min_qty" value="<?= e((string)($r['min_qty']??1)) ?>"></div><div class="field"><label>Maximum qty</label><input type="number" min="0.001" step="0.001" name="max_qty" value="<?= e((string)($r['max_qty']??'')) ?>"></div><div class="field"><label>Shipping class</label><input name="shipping_class" value="<?= e($r['shipping_class']?:'standard') ?>"></div><div class="field admin-checks"><label><input type="checkbox" name="tax_inclusive"<?= !isset($r['tax_inclusive'])||$r['tax_inclusive']?' checked':'' ?>> Price includes tax</label><label><input type="checkbox" name="cart_enabled"<?= $r['cart_enabled']?' checked':'' ?>> Enable cart</label></div><div class="field full"><small class="muted">Public catalogue: <?= $r['is_public']?'yes':'no' ?>. Cart visibility also requires the V4 publication gate and released V5 inventory.</small></div><div class="field full"><button class="btn">Save</button></div></form></details><?php endforeach;?></div></section><?php endif;?>
<?php require __DIR__.'/_footer.php';?>
