<?php
$adminTitle='Customers';require __DIR__.'/_header.php';require_once __DIR__.'/../includes/commerce.php';require_once __DIR__.'/../includes/customer_addresses.php';$pdo=db();$ready=commerce_schema_ready($pdo);$error='';$view=(int)($_GET['view']??$_POST['customer_id']??0);$q=trim((string)($_GET['q']??''));
if($ready&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{try{$active=(int)($_POST['active']??0)===1?1:0;$pdo->prepare('UPDATE customer_accounts SET is_active=:active WHERE id=:id')->execute(['active'=>$active,'id'=>$view]);admin_audit($pdo,'customer.status','customer',(string)$view,$active?'Enabled customer account':'Disabled customer account');header('Location: customers.php?view='.$view.'&saved=1');exit;}catch(Throwable $e){$error='Customer status could not be updated.';}}
}
$params=[];$where='';if($q!==''){$where='WHERE c.email LIKE :q OR c.first_name LIKE :q OR c.last_name LIKE :q OR c.company LIKE :q';$params['q']='%'.$q.'%';}
$sql="SELECT c.*,COUNT(o.id) order_count,COALESCE(SUM(CASE WHEN o.payment_status='Paid' THEN o.grand_total ELSE 0 END),0) paid_value,MAX(o.created_at) last_order_at FROM customer_accounts c LEFT JOIN sales_orders o ON o.customer_id=c.id $where GROUP BY c.id ORDER BY c.created_at DESC LIMIT 300";$stmt=$ready?$pdo->prepare($sql):null;if($stmt){$stmt->execute($params);$customers=$stmt->fetchAll();}else$customers=[];
$customer=null;$addresses=[];$orders=[];if($ready&&$view){$s=$pdo->prepare('SELECT * FROM customer_accounts WHERE id=:id');$s->execute(['id'=>$view]);$customer=$s->fetch()?:null;if($customer){$addresses=customer_addresses($pdo,$view);$s=$pdo->prepare('SELECT * FROM sales_orders WHERE customer_id=:id ORDER BY created_at DESC');$s->execute(['id'=>$view]);$orders=$s->fetchAll();}}
?>
<div class="admin-heading"><div><div class="eyebrow">CRM</div><h1>Customers</h1></div><form method="get" class="inline-select"><input name="q" value="<?= e($q) ?>" placeholder="Search email, name or company"><button class="btn">Search</button></form></div>
<?php if(!$ready):?><div class="alert error">V6 commerce is not installed.</div><?php endif;?><?php if(isset($_GET['saved'])):?><div class="alert success">Customer account status updated.</div><?php endif;?><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?>
<?php if($customer):?><section class="card"><div class="section-heading"><div><h2><?= e($customer['first_name'].' '.$customer['last_name']) ?></h2><p class="muted"><?= e($customer['email']) ?><?= $customer['company']?' · '.e($customer['company']):'' ?></p></div><span class="status-pill"><?= $customer['is_active']?'Active':'Disabled' ?></span></div><div class="grid-2"><div><h3>Addresses</h3><?php foreach($addresses as $a):?><p><strong><?= e($a['label']) ?><?= $a['is_default']?' · Default':'' ?></strong><br><?= e($a['address_line1']) ?><?= $a['address_line2']?'<br>'.e($a['address_line2']):'' ?><br><?= e($a['city'].', '.$a['province'].' '.$a['postal_code']) ?></p><?php endforeach;?><?php if(!$addresses):?><p class="muted">No saved addresses.</p><?php endif;?></div><div><h3>Account control</h3><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="customer_id" value="<?= (int)$customer['id'] ?>"><input type="hidden" name="active" value="<?= $customer['is_active']?0:1 ?>"><p>Registered <?= e($customer['created_at']) ?><br>Last login <?= e($customer['last_login_at']?:'—') ?></p><button class="btn"><?= $customer['is_active']?'Disable account':'Enable account' ?></button></form></div></div><h3>Orders</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>Date</th><th>Payment</th><th>Fulfilment</th><th>Total</th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><a href="orders.php?view=<?= (int)$o['id'] ?>"><?= e($o['order_number']) ?></a></td><td><?= e($o['created_at']) ?></td><td><?= e($o['payment_status']) ?></td><td><?= e($o['fulfilment_status']) ?></td><td><?= e($o['currency']) ?> <?= number_format((float)$o['grand_total'],2) ?></td></tr><?php endforeach;?><?php if(!$orders):?><tr><td colspan="5">No orders yet.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
<?php if($ready):?><section class="card admin-section-gap"><h2>Registered customers</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Company</th><th>Orders</th><th>Paid value</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($customers as $c):?><tr><td><?= e($c['first_name'].' '.$c['last_name']) ?><br><small><?= e($c['email']) ?></small></td><td><?= e($c['company']) ?></td><td><?= (int)$c['order_count'] ?><br><small><?= e($c['last_order_at']?:'—') ?></small></td><td><?= commerce_money((float)$c['paid_value']) ?></td><td><?= $c['is_active']?'Active':'Disabled' ?></td><td><a href="customers.php?view=<?= (int)$c['id'] ?>">Open</a></td></tr><?php endforeach;?><?php if(!$customers):?><tr><td colspan="6">No customers found.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
<?php require __DIR__.'/_footer.php';?>
