<?php
$adminTitle='Enquiries'; require __DIR__.'/_header.php'; $pdo=db(); $error='';
if($pdo && $_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.'; else{$id=(int)($_POST['id']??0);$status=(string)($_POST['status']??'new');$notes=trim((string)($_POST['admin_notes']??''));if(!in_array($status,['new','in_progress','closed'],true))$status='new';$pdo->prepare('UPDATE enquiries SET status=:status,admin_notes=:notes WHERE id=:id')->execute(['status'=>$status,'notes'=>$notes,'id'=>$id]);header('Location: enquiries.php?view='.$id.'&saved=1');exit;}
}
$view=null;if($pdo&&isset($_GET['view'])){$s=$pdo->prepare('SELECT * FROM enquiries WHERE id=:id');$s->execute(['id'=>(int)$_GET['view']]);$view=$s->fetch()?:null;}
$rows=$pdo?$pdo->query('SELECT * FROM enquiries ORDER BY submitted_at DESC LIMIT 250')->fetchAll():[];
?>
<div class="admin-heading"><div><div class="eyebrow">Inbox</div><h1>Enquiries</h1></div></div><?php if(isset($_GET['saved'])):?><div class="alert success">Enquiry updated.</div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if($view):?><section class="card admin-enquiry"><div class="admin-heading"><div><h2><?=e($view['name'])?></h2><p class="muted"><?=e($view['email'])?><?= $view['company']?' · '.e($view['company']):'' ?></p></div><span class="tag"><?=e($view['topic'])?></span></div><pre class="message-pre"><?=e($view['message'])?></pre><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=(int)$view['id']?>"><div class="form-grid"><div class="field"><label>Status</label><select name="status"><?php foreach(['new'=>'New','in_progress'=>'In progress','closed'=>'Closed'] as $k=>$v):?><option value="<?=e($k)?>"<?=($view['status']??'new')===$k?' selected':''?>><?=e($v)?></option><?php endforeach;?></select></div><div class="field full"><label>Internal notes</label><textarea name="admin_notes"><?=e($view['admin_notes']??'')?></textarea></div><div class="field full"><button class="btn primary">Save enquiry</button></div></div></form></section><?php endif;?>
<section class="card"><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Name</th><th>Topic</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><?=e($r['submitted_at'])?></td><td><?=e($r['name'])?></td><td><?=e($r['topic'])?></td><td><?=e($r['status']??'new')?></td><td><a href="?view=<?=(int)$r['id']?>">Open</a></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="5">No database enquiries yet.</td></tr><?php endif;?></tbody></table></div></section>
<?php require __DIR__.'/_footer.php';?>
