<?php
require_once __DIR__.'/../includes/auth.php';require_admin();require_once __DIR__.'/../includes/commerce.php';require_once __DIR__.'/../includes/audit.php';$pdo=db();
function export_cell(mixed $value): string{$v=(string)($value??'');if($v!==''&&in_array($v[0],['=','+','-','@'],true))$v="'".$v;return $v;}
function export_csv(string $filename,array $headers,iterable $rows): never{header('Content-Type: text/csv; charset=UTF-8');header('Content-Disposition: attachment; filename="'.$filename.'"');$out=fopen('php://output','wb');fputcsv($out,$headers);foreach($rows as $row)fputcsv($out,array_map('export_cell',array_values($row)));fclose($out);exit;}
$type=(string)($_GET['download']??'');
if($pdo&&$type!==''){
    if($type==='orders'){$rows=$pdo->query('SELECT order_number,created_at,email,first_name,last_name,company,province,payment_status,fulfilment_status,currency,subtotal,shipping_total,tax_total,grand_total FROM sales_orders ORDER BY created_at DESC')->fetchAll(PDO::FETCH_ASSOC);admin_audit($pdo,'export.download','orders',null,'Downloaded orders CSV',['rows'=>count($rows)]);export_csv('moleqra-orders-'.date('Ymd').'.csv',array_keys($rows[0]??['order_number'=>'','created_at'=>'','email'=>'','first_name'=>'','last_name'=>'','company'=>'','province'=>'','payment_status'=>'','fulfilment_status'=>'','currency'=>'','subtotal'=>'','shipping_total'=>'','tax_total'=>'','grand_total'=>'']),$rows);}
    if($type==='customers'){$rows=$pdo->query('SELECT c.id,c.email,c.first_name,c.last_name,c.company,c.phone,c.is_active,c.created_at,c.last_login_at,COUNT(o.id) order_count,COALESCE(SUM(CASE WHEN o.payment_status IN (\'Paid\',\'Partially refunded\') THEN o.grand_total ELSE 0 END),0) paid_value FROM customer_accounts c LEFT JOIN sales_orders o ON o.customer_id=c.id GROUP BY c.id ORDER BY c.created_at DESC')->fetchAll(PDO::FETCH_ASSOC);admin_audit($pdo,'export.download','customers',null,'Downloaded customers CSV',['rows'=>count($rows)]);export_csv('moleqra-customers-'.date('Ymd').'.csv',array_keys($rows[0]??['id'=>'','email'=>'','first_name'=>'','last_name'=>'','company'=>'','phone'=>'','is_active'=>'','created_at'=>'','last_login_at'=>'','order_count'=>'','paid_value'=>'']),$rows);}
    if($type==='products'){$rows=$pdo->query('SELECT p.id,p.sku,p.name,p.category,p.format,p.status,p.purity_label,p.featured,p.is_public,p.updated_at,pc.price,pc.currency,pc.cart_enabled FROM products p LEFT JOIN product_commerce pc ON pc.product_id=p.id ORDER BY p.sort_order,p.name')->fetchAll(PDO::FETCH_ASSOC);admin_audit($pdo,'export.download','products',null,'Downloaded products CSV',['rows'=>count($rows)]);export_csv('moleqra-products-'.date('Ymd').'.csv',array_keys($rows[0]??['id'=>'','sku'=>'','name'=>'','category'=>'','format'=>'','status'=>'','purity_label'=>'','featured'=>'','is_public'=>'','updated_at'=>'','price'=>'','currency'=>'','cart_enabled'=>'']),$rows);}
    if($type==='inventory'){$rows=$pdo->query('SELECT b.id,p.sku,p.name,b.batch_number,b.status,b.units_on_hand,b.received_at,b.expiry_date,b.retest_date,b.storage_location FROM inventory_batches b JOIN products p ON p.id=b.product_id ORDER BY p.name,b.received_at DESC')->fetchAll(PDO::FETCH_ASSOC);admin_audit($pdo,'export.download','inventory',null,'Downloaded inventory CSV',['rows'=>count($rows)]);export_csv('moleqra-inventory-'.date('Ymd').'.csv',array_keys($rows[0]??['id'=>'','sku'=>'','name'=>'','batch_number'=>'','status'=>'','units_on_hand'=>'','received_at'=>'','expiry_date'=>'','retest_date'=>'','storage_location'=>'']),$rows);}
}
$adminTitle='Exports';require __DIR__.'/_header.php';?>
<div class="admin-heading"><div><div class="eyebrow">Operations</div><h1>Data exports</h1></div></div><div class="grid-2"><section class="card"><h2>Orders</h2><p class="muted">Operational sales-order export including customer, payment, fulfilment and totals.</p><a class="btn" href="exports.php?download=orders">Download orders CSV</a></section><section class="card"><h2>Customers</h2><p class="muted">Customer account and aggregate order data. Handle this export as personal information.</p><a class="btn" href="exports.php?download=customers">Download customers CSV</a></section><section class="card"><h2>Products</h2><p class="muted">Master catalogue and base commerce settings.</p><a class="btn" href="exports.php?download=products">Download products CSV</a></section><section class="card"><h2>Inventory</h2><p class="muted">Batch-level stock and release-state export.</p><a class="btn" href="exports.php?download=inventory">Download inventory CSV</a></section></div><section class="card admin-section-gap"><h2>Security note</h2><p class="muted">CSV values that begin with spreadsheet formula characters are prefixed before export to reduce formula-injection risk. Customer and order exports still contain personal information and should be stored and shared appropriately.</p></section><?php require __DIR__.'/_footer.php';?>
