<?php
$adminTitle='Newsletter';require __DIR__.'/_header.php';require_once __DIR__.'/../includes/newsletter.php';require_once __DIR__.'/../includes/audit.php';
$pdo=db();$ready=$pdo&&newsletter_schema_ready($pdo);$error='';$message='';$edit=(int)($_GET['edit']??$_POST['campaign_id']??0);
if($ready&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';
 else{try{$action=(string)($_POST['action']??'');$adminId=(int)(admin_user()['id']??0)?:null;
   if($action==='save_campaign'){
      $id=(int)($_POST['campaign_id']??0);$name=trim((string)($_POST['name']??''));$subject=trim((string)($_POST['subject_template']??''));$body=trim((string)($_POST['body_html']??''));$scheduled=trim((string)($_POST['scheduled_at']??''));if($scheduled!==''){$scheduled=str_replace('T',' ',$scheduled);if(strlen($scheduled)===16)$scheduled.=':00';}else $scheduled=null;$batch=max(1,min(100,(int)($_POST['batch_limit']??50)));
      if($name===''||$subject===''||$body==='')throw new RuntimeException('Name, subject and body are required.');
      if($id){$attempts=$pdo->prepare("SELECT COUNT(*) FROM newsletter_queue WHERE campaign_id=:id AND attempts>0");$attempts->execute(['id'=>$id]);if((int)$attempts->fetchColumn()>0)throw new RuntimeException('This campaign has already started sending and its content is locked.');$pdo->beginTransaction();$pdo->prepare("UPDATE newsletter_campaigns SET name=:name,subject_template=:subject,body_html=:body,scheduled_at=:scheduled,batch_limit=:batch WHERE id=:id AND status IN ('Draft','Paused')")->execute(['name'=>$name,'subject'=>$subject,'body'=>$body,'scheduled'=>$scheduled,'batch'=>$batch,'id'=>$id]);$pdo->prepare("DELETE FROM newsletter_queue WHERE campaign_id=:id AND status IN ('Pending','Failed')")->execute(['id'=>$id]);$added=newsletter_queue_campaign($pdo,$id);$pdo->commit();$message="Campaign updated with $added subscriber(s) queued.";}
      else{$pdo->prepare("INSERT INTO newsletter_campaigns(name,subject_template,body_html,status,scheduled_at,batch_limit,created_by) VALUES(:name,:subject,:body,'Draft',:scheduled,:batch,:admin)")->execute(['name'=>$name,'subject'=>$subject,'body'=>$body,'scheduled'=>$scheduled,'batch'=>$batch,'admin'=>$adminId]);$id=(int)$pdo->lastInsertId();$added=newsletter_queue_campaign($pdo,$id);$message="Campaign created with $added subscriber(s) queued.";}
      admin_audit($pdo,'newsletter.campaign_save','newsletter_campaign',(string)$id,'Saved newsletter campaign');
   }elseif($action==='status'){
      $id=(int)($_POST['campaign_id']??0);$status=(string)($_POST['status']??'Paused');if(!in_array($status,['Running','Paused'],true))throw new RuntimeException('Invalid status.');$pdo->prepare("UPDATE newsletter_campaigns SET status=:status WHERE id=:id AND status<>'Completed'")->execute(['status'=>$status,'id'=>$id]);admin_audit($pdo,'newsletter.status','newsletter_campaign',(string)$id,'Changed newsletter status',['status'=>$status]);$message='Campaign status updated.';
   }elseif($action==='process'){
      $id=(int)($_POST['campaign_id']??0);$r=newsletter_process_campaign($pdo,$id,25);admin_audit($pdo,'newsletter.process','newsletter_campaign',(string)$id,'Processed newsletter batch',$r);$message='Newsletter batch: '.$r['sent'].' sent, '.$r['failed'].' failed, '.$r['remaining'].' remaining.';
   }elseif($action==='subscriber_status'){
      $id=(int)($_POST['subscriber_id']??0);$status=(string)($_POST['status']??'Unsubscribed');if(!in_array($status,['Subscribed','Unsubscribed'],true))throw new RuntimeException('Invalid subscriber state.');if($status==='Subscribed')$pdo->prepare("UPDATE newsletter_subscribers SET status='Subscribed',confirmed_at=COALESCE(confirmed_at,NOW()),unsubscribed_at=NULL WHERE id=:id")->execute(['id'=>$id]);else $pdo->prepare("UPDATE newsletter_subscribers SET status='Unsubscribed',unsubscribed_at=NOW() WHERE id=:id")->execute(['id'=>$id]);admin_audit($pdo,'newsletter.subscriber_status','newsletter_subscriber',(string)$id,'Changed newsletter subscriber state',['status'=>$status]);$message='Subscriber updated.';
   }
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Newsletter operation failed.';}}
}
$campaigns=$ready?$pdo->query("SELECT c.*,(SELECT COUNT(*) FROM newsletter_queue q WHERE q.campaign_id=c.id AND q.status='Sent') sent,(SELECT COUNT(*) FROM newsletter_queue q WHERE q.campaign_id=c.id AND q.status='Pending') pending,(SELECT COUNT(*) FROM newsletter_queue q WHERE q.campaign_id=c.id AND q.status='Failed') failed FROM newsletter_campaigns c ORDER BY c.created_at DESC")->fetchAll():[];
$subscribers=$ready?$pdo->query("SELECT * FROM newsletter_subscribers ORDER BY created_at DESC LIMIT 300")->fetchAll():[];
$current=null;if($edit){foreach($campaigns as $c)if((int)$c['id']===$edit)$current=$c;}
?>
<div class="admin-heading"><div><div class="eyebrow">Retention</div><h1>Newsletter</h1><p class="muted">Confirmed subscriptions, campaign scheduling and auditable batch delivery.</p></div></div>
<?php if($message):?><div class="alert success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$ready):?><div class="alert error">Newsletter/community migration 010 is not installed.</div><?php else:?>
<div class="admin-two-col admin-section-gap">
<section class="card"><h2><?= $current?'Edit campaign':'Create campaign' ?></h2><form method="post" id="newsletter-editor"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_campaign"><input type="hidden" name="campaign_id" value="<?=(int)($current['id']??0)?>"><div class="form-grid"><div class="field full"><label>Name</label><input name="name" maxlength="160" required value="<?=e($current['name']??'')?>"></div><div class="field full"><label>Subject</label><input id="newsletter-subject" name="subject_template" maxlength="220" required value="<?=e($current['subject_template']??'Moleqra progress update')?>"></div><div class="field full"><label>HTML body</label><textarea id="newsletter-body" name="body_html" style="min-height:320px" required><?=e($current['body_html']??'<p>Here is the latest progress update from Moleqra.</p>')?></textarea></div><div class="field"><label>Scheduled at</label><input type="datetime-local" name="scheduled_at" value="<?=!empty($current['scheduled_at'])?e(date('Y-m-d\TH:i',strtotime($current['scheduled_at']))):''?>"></div><div class="field"><label>Batch size</label><input type="number" name="batch_limit" min="1" max="100" value="<?=(int)($current['batch_limit']??50)?>"></div><div class="field full"><button class="btn primary">Save &amp; rebuild unsent queue</button></div></div></form></section>
<section class="card campaign-preview-card"><h2>Live preview</h2><div class="campaign-preview-subject"><span>Subject</span><strong id="newsletter-preview-subject"></strong></div><iframe id="newsletter-preview-frame" class="campaign-preview-frame" sandbox title="Newsletter preview"></iframe></section>
</div>
<section class="card admin-section-gap"><h2>Campaigns</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Campaign</th><th>Status</th><th>Queue</th><th>Schedule</th><th>Actions</th></tr></thead><tbody><?php foreach($campaigns as $c):?><tr><td><strong><?=e($c['name'])?></strong><br><small><?=e($c['subject_template'])?></small></td><td><?=e($c['status'])?></td><td><?=(int)$c['sent']?> sent · <?=(int)$c['pending']?> pending<?= (int)$c['failed']?' · '.(int)$c['failed'].' failed':'' ?></td><td><?=e($c['scheduled_at']?:'Immediate when run')?></td><td class="table-actions"><a href="newsletter.php?edit=<?=(int)$c['id']?>">Preview / edit</a><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="status"><input type="hidden" name="campaign_id" value="<?=(int)$c['id']?>"><input type="hidden" name="status" value="<?= $c['status']==='Running'?'Paused':'Running' ?>"><button class="link-button"><?= $c['status']==='Running'?'Pause':'Run' ?></button></form><?php if($c['status']==='Running'):?><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="process"><input type="hidden" name="campaign_id" value="<?=(int)$c['id']?>"><button class="link-button">Send next batch</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$campaigns):?><tr><td colspan="5">No newsletter campaigns yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card admin-section-gap"><h2>Subscribers</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Email</th><th>Status</th><th>Source</th><th>Confirmed</th><th>Last sent</th><th>Action</th></tr></thead><tbody><?php foreach($subscribers as $s):?><tr><td><?=e($s['email'])?></td><td><?=e($s['status'])?></td><td><?=e($s['source'])?></td><td><?=e($s['confirmed_at']?:'—')?></td><td><?=e($s['last_sent_at']?:'—')?></td><td><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="subscriber_status"><input type="hidden" name="subscriber_id" value="<?=(int)$s['id']?>"><input type="hidden" name="status" value="<?= $s['status']==='Subscribed'?'Unsubscribed':'Subscribed' ?>"><button class="link-button"><?= $s['status']==='Subscribed'?'Unsubscribe':'Subscribe' ?></button></form></td></tr><?php endforeach;?></tbody></table></div></section>
<script>
(()=>{const subject=document.getElementById('newsletter-subject'),body=document.getElementById('newsletter-body'),sout=document.getElementById('newsletter-preview-subject'),frame=document.getElementById('newsletter-preview-frame');if(!subject||!body||!sout||!frame)return;const render=()=>{sout.textContent=subject.value||'Newsletter preview';frame.srcdoc='<!doctype html><html><body style="font-family:Arial,sans-serif;background:#f4f6f8;padding:24px"><div style="max-width:680px;margin:auto;background:white;padding:26px;border:1px solid #dde3ea">'+body.value+'<p style="margin-top:28px;color:#65717e;font-size:12px">You are receiving this because you subscribed to Moleqra updates. Unsubscribe links are inserted when sent.</p></div></body></html>';};subject.addEventListener('input',render);body.addEventListener('input',render);render();})();
</script>
<?php endif;?>
<?php require __DIR__.'/_footer.php';?>
