<?php
$adminTitle='Orders';require __DIR__.'/_header.php';require_once __DIR__.'/../includes/commerce.php';require_once __DIR__.'/../includes/commercial_ops.php';require_once __DIR__.'/../includes/notifications.php';require_once __DIR__.'/../includes/invoices.php';
$pdo=db();$ready=commerce_schema_ready($pdo);$opsReady=commercial_ops_schema_ready($pdo);$error='';$view=(int)($_GET['view']??$_POST['order_id']??0);$paymentFilter=trim((string)($_GET['payment']??''));$q=trim((string)($_GET['q']??''));
if($pdo&&$ready&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{try{$action=(string)($_POST['action']??'');
  if($action==='fulfil'){commerce_fulfil_order($pdo,$view,trim((string)($_POST['courier']??'')),trim((string)($_POST['service']??''))?:null,trim((string)($_POST['tracking']??''))?:null,trim((string)($_POST['notes']??''))?:null,(int)(admin_user()['id']??0)?:null);admin_audit($pdo,'order.fulfil','order',(string)$view,'Fulfilled and dispatched order',['courier'=>trim((string)($_POST['courier']??''))]);try{notify_order_dispatched($pdo,$view);}catch(Throwable $mailError){error_log('Moleqra dispatch notification failed: '.$mailError->getMessage());}header('Location: orders.php?view='.$view.'&fulfilled=1');exit;}
  if($action==='note'){$pdo->prepare('UPDATE sales_orders SET admin_note=:note WHERE id=:id')->execute(['note'=>trim((string)($_POST['admin_note']??''))?:null,'id'=>$view]);admin_audit($pdo,'order.note','order',(string)$view,'Updated admin order note');header('Location: orders.php?view='.$view.'&saved=1');exit;}
  if($action==='issue_invoice'){if(!commercial_ops_schema_ready($pdo))throw new RuntimeException('V7 invoice records are unavailable.');$invoice=invoice_issue_if_needed($pdo,$view);if(!$invoice)throw new RuntimeException('An invoice can only be issued for a paid order.');admin_audit($pdo,'invoice.issue','order',(string)$view,'Issued invoice',['invoice_number'=>$invoice['invoice_number']]);header('Location: orders.php?view='.$view.'&invoice=1');exit;}
  if($action==='payment_reminder'){if(!$opsReady)throw new RuntimeException('V7 notification records are unavailable.');notify_payment_reminder($pdo,$view);admin_audit($pdo,'order.payment_reminder','order',(string)$view,'Requested payment reminder');header('Location: orders.php?view='.$view.'&reminder=1');exit;}
  if($action==='cancel'){$s=$pdo->prepare('SELECT payment_status,fulfilment_status FROM sales_orders WHERE id=:id');$s->execute(['id'=>$view]);$state=$s->fetch();if(!$state||$state['payment_status']!=='Pending'||$state['fulfilment_status']==='Fulfilled')throw new RuntimeException('Only unpaid, unfulfilled orders can be cancelled here. Paid orders require the refund workflow.');$pdo->beginTransaction();$pdo->prepare("UPDATE sales_orders SET status='Cancelled',payment_status='Cancelled',cancelled_at=NOW() WHERE id=:id")->execute(['id'=>$view]);$pdo->prepare("UPDATE stock_reservations SET status='Released' WHERE order_id=:id AND status='Active'")->execute(['id'=>$view]);$pdo->commit();admin_audit($pdo,'order.cancel','order',(string)$view,'Cancelled unpaid order');header('Location: orders.php?view='.$view.'&cancelled=1');exit;}
  if($action==='cleanup'){commerce_cleanup_expired_reservations($pdo);admin_audit($pdo,'order.reservation_cleanup','orders',null,'Released expired reservations');header('Location: orders.php?cleaned=1');exit;}
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Order operation failed.';}}
}
$where=[];$params=[];if($paymentFilter!==''){$where[]='payment_status=:payment';$params['payment']=$paymentFilter;}if($q!==''){$where[]='(order_number LIKE :q OR email LIKE :q OR first_name LIKE :q OR last_name LIKE :q)';$params['q']='%'.$q.'%';}$sql='SELECT * FROM sales_orders'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY created_at DESC LIMIT 400';$orders=[];if($ready){$stmt=$pdo->prepare($sql);$stmt->execute($params);$orders=$stmt->fetchAll();}
$order=null;$items=[];$reservations=[];$payments=[];$shipments=[];$invoice=null;$refunds=[];$notifications=[];$shippingQuote=null;
if($ready&&$view){$s=$pdo->prepare('SELECT * FROM sales_orders WHERE id=:id');$s->execute(['id'=>$view]);$order=$s->fetch()?:null;if($order){$items=commerce_order_items($pdo,$view);$s=$pdo->prepare('SELECT r.*,b.batch_number,p.sku FROM stock_reservations r JOIN inventory_batches b ON b.id=r.batch_id JOIN products p ON p.id=b.product_id WHERE r.order_id=:id ORDER BY r.id');$s->execute(['id'=>$view]);$reservations=$s->fetchAll();$s=$pdo->prepare('SELECT * FROM payment_transactions WHERE order_id=:id ORDER BY received_at DESC');$s->execute(['id'=>$view]);$payments=$s->fetchAll();$s=$pdo->prepare('SELECT * FROM order_shipments WHERE order_id=:id ORDER BY created_at DESC');$s->execute(['id'=>$view]);$shipments=$s->fetchAll();if($opsReady){$invoice=invoice_for_order($pdo,$view);$s=$pdo->prepare('SELECT * FROM order_refunds WHERE order_id=:id ORDER BY created_at DESC');$s->execute(['id'=>$view]);$refunds=$s->fetchAll();$s=$pdo->prepare('SELECT * FROM commerce_notifications WHERE order_id=:id ORDER BY created_at DESC');$s->execute(['id'=>$view]);$notifications=$s->fetchAll();$s=$pdo->prepare('SELECT * FROM order_shipping_quotes WHERE order_id=:id');$s->execute(['id'=>$view]);$shippingQuote=$s->fetch()?:null;}}}
?>
<div class="admin-heading"><div><div class="eyebrow">Sales</div><h1>Orders</h1></div><div class="admin-actions"><a class="btn" href="commerce.php">Commerce</a><?php if($opsReady):?><a class="btn" href="refunds.php">Refunds</a><?php endif;?></div></div>
<?php if(!$ready):?><div class="alert error">V6 commerce is not installed.</div><?php endif;?><?php if($ready&&!$opsReady):?><div class="alert error">V7 commercial operations is not installed. Order processing still works, but invoices/refunds/notifications are unavailable.</div><?php endif;?><?php if(isset($_GET['fulfilled'])):?><div class="alert success">Order fulfilled, reserved stock consumed and dispatch notification recorded.</div><?php endif;?><?php if(isset($_GET['saved'])):?><div class="alert success">Order note saved.</div><?php endif;?><?php if(isset($_GET['invoice'])):?><div class="alert success">Invoice issued.</div><?php endif;?><?php if(isset($_GET['reminder'])):?><div class="alert success">Payment reminder notification recorded.</div><?php endif;?><?php if(isset($_GET['cancelled'])):?><div class="alert success">Order cancelled.</div><?php endif;?><?php if(isset($_GET['cleaned'])):?><div class="alert success">Expired unpaid reservations were released.</div><?php endif;?><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?>
<?php if($order):?><section class="card"><div class="section-heading"><div><h2><?= e($order['order_number']) ?></h2><p class="muted"><?= e($order['email']) ?> · <?= e($order['created_at']) ?></p></div><span class="status-pill"><?= e($order['status']) ?></span></div><div class="supplier-summary-grid"><div><span class="muted">Payment</span><p><strong><?= e($order['payment_status']) ?></strong><br><?= e($order['currency']) ?> <?= number_format((float)$order['grand_total'],2) ?></p></div><div><span class="muted">Fulfilment</span><p><strong><?= e($order['fulfilment_status']) ?></strong><?php if($shippingQuote):?><br><?= e($shippingQuote['rule_name']) ?> · <?= e($order['currency']) ?> <?= number_format((float)$shippingQuote['amount'],2) ?><?php endif;?></p></div><div><span class="muted">Ship to</span><p><?= e($order['first_name'].' '.$order['last_name']) ?><br><?= e($order['city'].', '.$order['province']) ?></p></div></div>
<div class="admin-actions admin-section-gap"><a class="btn" href="../order.php?token=<?= e($order['order_token']) ?>" target="_blank">Customer view</a><?php if($invoice):?><a class="btn" href="../invoice.php?token=<?= e($order['order_token']) ?>" target="_blank">Invoice <?= e($invoice['invoice_number']) ?></a><?php elseif($opsReady&&$order['payment_status']==='Paid'):?><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="issue_invoice"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button class="btn">Issue invoice</button></form><?php endif;?><?php if($opsReady&&in_array($order['payment_status'],['Paid','Partially refunded','Refunded'],true)):?><a class="btn" href="refunds.php?order=<?= (int)$order['id'] ?>">Refunds</a><?php endif;?></div>
<h3>Items</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>Qty</th><th>Line total</th></tr></thead><tbody><?php foreach($items as $i):?><tr><td><?= e($i['sku'].' · '.$i['product_name'].(!empty($i['variant_label'])?' · '.$i['variant_label']:'')) ?></td><td><?= e((string)$i['quantity']) ?></td><td><?= e($order['currency']) ?> <?= number_format((float)$i['line_total'],2) ?></td></tr><?php endforeach;?></tbody></table></div>
<h3>Batch reservations</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Batch</th><th>Qty</th><th>Status</th></tr></thead><tbody><?php foreach($reservations as $r):?><tr><td><?= e($r['sku'].' · '.$r['batch_number']) ?></td><td><?= e((string)$r['quantity']) ?></td><td><?= e($r['status']) ?></td></tr><?php endforeach;?></tbody></table></div>
<h3>Payment audit</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Received</th><th>Gateway ID</th><th>Status</th><th>Amount</th><th>Checks</th></tr></thead><tbody><?php foreach($payments as $p):?><tr><td><?= e($p['received_at']) ?></td><td><?= e($p['gateway_payment_id']) ?></td><td><?= e($p['gateway_status']) ?></td><td><?= $p['amount_gross']!==null?e($order['currency']).' '.number_format((float)$p['amount_gross'],2):'—' ?></td><td><?= $p['signature_valid']?'Sig✓':'Sig✗' ?> · <?= $p['source_valid']?'Src✓':'Src✗' ?> · <?= $p['amount_valid']?'Amt✓':'Amt✗' ?> · <?= $p['server_valid']?'Srv✓':'Srv✗' ?></td></tr><?php endforeach;?><?php if(!$payments):?><tr><td colspan="5">No gateway notifications recorded.</td></tr><?php endif;?></tbody></table></div>
<?php if($opsReady):?><h3>Refunds</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Refund</th><th>Amount</th><th>Status</th><th>Reason</th></tr></thead><tbody><?php foreach($refunds as $r):?><tr><td><?= e($r['refund_number']) ?></td><td><?= e($r['currency']) ?> <?= number_format((float)$r['amount'],2) ?></td><td><?= e($r['status']) ?></td><td><?= e($r['reason']) ?></td></tr><?php endforeach;?><?php if(!$refunds):?><tr><td colspan="4">No refunds recorded.</td></tr><?php endif;?></tbody></table></div><h3>Customer notifications</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Date</th><th>Type</th><th>Recipient</th><th>Status</th></tr></thead><tbody><?php foreach($notifications as $n):?><tr><td><?= e($n['created_at']) ?></td><td><?= e($n['notification_type']) ?></td><td><?= e($n['recipient']) ?></td><td><?= e($n['status']) ?><?= $n['error_message']?'<br><small>'.e($n['error_message']).'</small>':'' ?></td></tr><?php endforeach;?><?php if(!$notifications):?><tr><td colspan="4">No notifications recorded.</td></tr><?php endif;?></tbody></table></div><?php endif;?>
<h3>Shipments</h3><div class="table-wrap"><table class="data-table"><thead><tr><th>Dispatched</th><th>Courier</th><th>Tracking</th></tr></thead><tbody><?php foreach($shipments as $sh):?><tr><td><?= e($sh['dispatched_at']) ?></td><td><?= e(trim(($sh['courier']??'').' '.($sh['service']??''))) ?></td><td><?= e($sh['tracking_number']) ?></td></tr><?php endforeach;?><?php if(!$shipments):?><tr><td colspan="3">No shipments recorded.</td></tr><?php endif;?></tbody></table></div>
<?php if($order['payment_status']==='Pending'&&$order['fulfilment_status']!=='Fulfilled'):?><div class="admin-actions admin-section-gap"><?php if($opsReady):?><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="payment_reminder"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button class="btn" type="submit">Send payment reminder</button></form><?php endif;?><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="cancel"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><button class="btn" type="submit">Cancel unpaid order</button></form></div><?php endif;?>
<?php if($order['payment_status']==='Paid'&&$order['fulfilment_status']!=='Fulfilled'):?><form method="post" class="card admin-section-gap"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="fulfil"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><h3>Dispatch order</h3><div class="form-grid"><div class="field"><label>Courier</label><input name="courier" maxlength="100" required></div><div class="field"><label>Service</label><input name="service" maxlength="100"></div><div class="field full"><label>Tracking number</label><input name="tracking" maxlength="160"></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><button class="btn primary">Dispatch &amp; consume reserved stock</button></form><?php endif;?>
<form method="post" class="admin-section-gap"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="note"><input type="hidden" name="order_id" value="<?= (int)$order['id'] ?>"><div class="field"><label>Admin note</label><textarea name="admin_note"><?= e($order['admin_note']) ?></textarea></div><button class="btn">Save note</button></form></section><?php endif;?>
<?php if($ready):?><section class="card admin-section-gap"><div class="section-heading"><div><h2>Recent orders</h2><p class="muted">Search, filter, or release expired unpaid reservations.</p></div><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="cleanup"><button class="btn">Release expired reservations</button></form></div><form method="get" class="inline-select"><input name="q" value="<?= e($q) ?>" placeholder="Order, email or customer"><select name="payment"><option value="">All payments</option><?php foreach(['Pending','Paid','Partially refunded','Refunded','Cancelled','Expired'] as $st):?><option<?= $paymentFilter===$st?' selected':'' ?>><?= e($st) ?></option><?php endforeach;?></select><button class="btn">Filter</button></form><div class="table-wrap admin-section-gap"><table class="data-table"><thead><tr><th>Order</th><th>Customer</th><th>Payment</th><th>Fulfilment</th><th>Total</th><th></th></tr></thead><tbody><?php foreach($orders as $o):?><tr><td><?= e($o['order_number']) ?><br><small><?= e($o['created_at']) ?></small></td><td><?= e($o['email']) ?></td><td><?= e($o['payment_status']) ?></td><td><?= e($o['fulfilment_status']) ?></td><td><?= e($o['currency']) ?> <?= number_format((float)$o['grand_total'],2) ?></td><td><a href="orders.php?view=<?= (int)$o['id'] ?>">Open</a></td></tr><?php endforeach;?><?php if(!$orders):?><tr><td colspan="6">No orders found.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
<?php require __DIR__.'/_footer.php';?>
