<?php
$adminTitle='Prospect Outreach';
require_once __DIR__.'/../includes/auth.php';require_admin();
require_once __DIR__.'/../includes/outreach_automation.php';require_once __DIR__.'/../includes/audit.php';
$pdo=db();$error='';$message='';
if($pdo&&outreach_schema_ready($pdo)&&$_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';
    else{try{$action=(string)($_POST['action']??'');$adminId=(int)(admin_user()['id']??0)?:null;
        if($action==='save_template'){
            $id=(int)($_POST['template_id']??0);$name=trim((string)($_POST['name']??''));$subject=trim((string)($_POST['subject_template']??''));$body=trim((string)($_POST['body_html']??''));if($name===''||$subject===''||$body==='')throw new RuntimeException('Template name, subject and body are required.');
            if($id){$pdo->prepare('UPDATE supplier_outreach_templates SET name=:name,subject_template=:subject,body_html=:body,is_active=:active WHERE id=:id')->execute(['name'=>$name,'subject'=>$subject,'body'=>$body,'active'=>isset($_POST['is_active'])?1:0,'id'=>$id]);}
            else{$pdo->prepare('INSERT INTO supplier_outreach_templates(name,subject_template,body_html,is_active) VALUES(:name,:subject,:body,:active)')->execute(['name'=>$name,'subject'=>$subject,'body'=>$body,'active'=>isset($_POST['is_active'])?1:0]);$id=(int)$pdo->lastInsertId();}
            admin_audit($pdo,'outreach.template','supplier_outreach_template',(string)$id,'Saved supplier outreach template');$message='Template saved.';
        }elseif($action==='create_campaign'){
            $name=trim((string)($_POST['campaign_name']??''));$template=(int)($_POST['template_id']??0);if($name===''||$template<1)throw new RuntimeException('Campaign name and template are required.');
            $daily=max(1,min(50,(int)($_POST['daily_limit']??10)));$minDays=max(0,min(365,(int)($_POST['min_days_between_contacts']??30)));$follow=max(1,min(90,(int)($_POST['follow_up_days']??7)));$region=trim((string)($_POST['target_region']??''));$status=trim((string)($_POST['target_supplier_status']??'Prospect'));$start=trim((string)($_POST['scheduled_start']??''));if($start!==''){$start=str_replace('T',' ',$start);if(strlen($start)===16)$start.=':00';}else $start=null;
            $pdo->prepare("INSERT INTO supplier_outreach_campaigns(name,template_id,status,target_supplier_status,target_region,daily_limit,min_days_between_contacts,follow_up_days,scheduled_start,created_by) VALUES(:name,:template,'Draft',:status,:region,:daily,:min_days,:follow,:start,:admin)")->execute(['name'=>$name,'template'=>$template,'status'=>$status?:null,'region'=>$region?:null,'daily'=>$daily,'min_days'=>$minDays,'follow'=>$follow,'start'=>$start,'admin'=>$adminId]);$id=(int)$pdo->lastInsertId();$added=outreach_queue_campaign($pdo,$id);admin_audit($pdo,'outreach.campaign_create','supplier_outreach_campaign',(string)$id,'Created supplier outreach campaign',['queued'=>$added]);$message="Campaign created with $added queued prospect(s).";
        }elseif($action==='campaign_status'){
            $id=(int)($_POST['campaign_id']??0);$status=(string)($_POST['status']??'Paused');if(!in_array($status,['Running','Paused'],true))throw new RuntimeException('Invalid campaign status.');$pdo->prepare('UPDATE supplier_outreach_campaigns SET status=:status WHERE id=:id')->execute(['status'=>$status,'id'=>$id]);admin_audit($pdo,'outreach.campaign_status','supplier_outreach_campaign',(string)$id,'Changed campaign status',['status'=>$status]);$message='Campaign status updated.';
        }elseif($action==='queue_campaign'){
            $id=(int)($_POST['campaign_id']??0);$added=outreach_queue_campaign($pdo,$id);$message="$added additional prospect(s) queued.";
        }elseif($action==='process_campaign'){
            $id=(int)($_POST['campaign_id']??0);$result=outreach_process_campaign($pdo,$id,5);admin_audit($pdo,'outreach.process','supplier_outreach_campaign',(string)$id,'Processed outreach batch',$result);$message='Outreach batch processed: '.$result['sent'].' sent, '.$result['failed'].' failed, '.$result['remaining'].' remaining.';
        }
    }catch(Throwable $e){error_log('Moleqra outreach admin failed: '.$e->getMessage());$error=$e instanceof RuntimeException?$e->getMessage():'Outreach operation failed.';}}
}
$templates=$pdo&&outreach_schema_ready($pdo)?$pdo->query('SELECT * FROM supplier_outreach_templates ORDER BY is_active DESC,name')->fetchAll():[];
$campaigns=$pdo&&outreach_schema_ready($pdo)?$pdo->query("SELECT c.*,t.name template_name,(SELECT COUNT(*) FROM supplier_outreach_queue q WHERE q.campaign_id=c.id) queued,(SELECT COUNT(*) FROM supplier_outreach_queue q WHERE q.campaign_id=c.id AND q.status='Sent') sent,(SELECT COUNT(*) FROM supplier_outreach_queue q WHERE q.campaign_id=c.id AND q.status='Pending') pending,(SELECT COUNT(*) FROM supplier_outreach_queue q WHERE q.campaign_id=c.id AND q.status='Failed') failed FROM supplier_outreach_campaigns c JOIN supplier_outreach_templates t ON t.id=c.template_id ORDER BY c.created_at DESC")->fetchAll():[];
$editTemplate=$templates[0]??null;if(isset($_GET['template'])){foreach($templates as $t)if((int)$t['id']===(int)$_GET['template'])$editTemplate=$t;}
require __DIR__.'/_header.php';
?>
<div class="admin-heading"><div><div class="eyebrow">Supplier automation</div><h1>Prospect outreach</h1><p class="muted">Queue supplier partnership emails with per-campaign limits, contact-spacing controls, opt-outs and an auditable outreach history.</p></div></div>
<?php if($message):?><div class="alert success"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="alert error"><?=e($error)?></div><?php endif;?>
<?php if(!$pdo||!outreach_schema_ready($pdo)):?><div class="alert error">V9 outreach automation is not installed. Run the System upgrade.</div><?php else:?>
<div class="notice"><strong>Delivery guard:</strong> automated prospect sending only runs when outbound email is explicitly enabled with the <code>mail</code> transport. Campaigns are capped at 50 emails/day and each supplier is queued once per campaign. Supplier opt-outs always take precedence.</div>
<div class="admin-two-col admin-section-gap">
<section class="card"><h2><?= $editTemplate?'Edit template':'Email template' ?></h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save_template"><input type="hidden" name="template_id" value="<?=(int)($editTemplate['id']??0)?>"><div class="form-grid"><div class="field full"><label>Name</label><input name="name" maxlength="140" value="<?=e($editTemplate['name']??'Formal first contact')?>"></div><div class="field full"><label>Subject template</label><input name="subject_template" maxlength="220" value="<?=e($editTemplate['subject_template']??'Retail / Reseller Partnership Enquiry – {{site_name}}')?>"></div><div class="field full"><label>HTML body</label><textarea name="body_html" style="min-height:360px"><?=e($editTemplate['body_html']??'')?></textarea><small class="muted">Available placeholders: {{supplier_name}}, {{contact_name}}, {{contact_greeting}}, {{site_name}}, {{contact_email}}, {{website}}</small></div><div class="field full"><label class="check-row"><input type="checkbox" name="is_active" value="1"<?=!isset($editTemplate['is_active'])||$editTemplate['is_active']?' checked':''?>> Active template</label></div><div class="field full"><button class="btn primary">Save template</button></div></div></form></section>
<section class="card"><h2>Create campaign</h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="create_campaign"><div class="form-grid"><div class="field full"><label>Campaign name</label><input name="campaign_name" maxlength="160" required placeholder="SA supplier introduction"></div><div class="field full"><label>Template</label><select name="template_id" required><?php foreach($templates as $t):?><option value="<?=(int)$t['id']?>"><?=e($t['name'])?></option><?php endforeach;?></select></div><div class="field"><label>Supplier status</label><select name="target_supplier_status"><option>Prospect</option><option>Contacted</option><option>Evaluating</option><option value="">Any status</option></select></div><div class="field"><label>Region (optional)</label><input name="target_region" maxlength="80" placeholder="South Africa"></div><div class="field"><label>Daily send limit</label><input type="number" name="daily_limit" min="1" max="50" value="10"></div><div class="field"><label>Minimum days between contacts</label><input type="number" name="min_days_between_contacts" min="0" max="365" value="30"></div><div class="field"><label>Follow-up after days</label><input type="number" name="follow_up_days" min="1" max="90" value="7"></div><div class="field"><label>Start at (optional)</label><input type="datetime-local" name="scheduled_start"></div><div class="field full"><button class="btn primary">Create &amp; queue campaign</button></div></div></form></section>
</div>
<section class="card admin-section-gap"><h2>Campaigns</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Campaign</th><th>Status</th><th>Queue</th><th>Limits</th><th>Last processed</th><th>Actions</th></tr></thead><tbody><?php foreach($campaigns as $c):?><tr><td><strong><?=e($c['name'])?></strong><br><small><?=e($c['template_name'])?><?= $c['target_region']?' · '.e($c['target_region']):'' ?></small></td><td><?=e($c['status'])?></td><td><?= (int)$c['sent'] ?> sent · <?= (int)$c['pending'] ?> pending<?= (int)$c['failed']?' · '.(int)$c['failed'].' failed':'' ?></td><td><?= (int)$c['daily_limit'] ?>/day<br><small><?= (int)$c['min_days_between_contacts'] ?> day spacing</small></td><td><?=e($c['last_processed_at']?:'—')?></td><td class="table-actions"><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="campaign_status"><input type="hidden" name="campaign_id" value="<?=(int)$c['id']?>"><input type="hidden" name="status" value="<?= $c['status']==='Running'?'Paused':'Running' ?>"><button class="link-button"><?= $c['status']==='Running'?'Pause':'Run' ?></button></form><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="queue_campaign"><input type="hidden" name="campaign_id" value="<?=(int)$c['id']?>"><button class="link-button">Refresh queue</button></form><?php if($c['status']==='Running'):?><form method="post" class="inline-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="process_campaign"><input type="hidden" name="campaign_id" value="<?=(int)$c['id']?>"><button class="link-button">Send next batch</button></form><?php endif;?></td></tr><?php endforeach;?><?php if(!$campaigns):?><tr><td colspan="6">No campaigns yet.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card admin-section-gap"><h2>Automation scheduling</h2><p>For automatic sending without a persistent worker, schedule:</p><pre><code>php /absolute/path/to/automation/outreach.php</code></pre><p class="muted">Alternatively call the HTTPS endpoint with <code>Authorization: Bearer &lt;outreach_key&gt;</code>. Copy <code>config/automation.example.php</code> to <code>config/automation.php</code> and use a long random secret. No automatic send occurs until a campaign is set to Running.</p></section>
<?php endif;?>
<?php require __DIR__.'/_footer.php';?>
