<?php
$adminTitle='Payments';require __DIR__.'/_header.php';require_once __DIR__.'/../includes/commerce.php';$pdo=db();$ready=$pdo&&db_table_exists('payment_reconciliations',$pdo);$error='';$view=(int)($_GET['view']??$_POST['transaction_id']??0);
if($ready&&$_SERVER['REQUEST_METHOD']==='POST'){
 if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{try{$stmt=$pdo->prepare('SELECT order_id FROM payment_transactions WHERE id=:id');$stmt->execute(['id'=>$view]);$orderId=(int)$stmt->fetchColumn();if(!$orderId)throw new RuntimeException('Payment transaction not found.');$sql='INSERT INTO payment_reconciliations(order_id,payment_transaction_id,reconciliation_status,notes,created_by) VALUES(:order,:payment,:status,:notes,:admin) ON DUPLICATE KEY UPDATE reconciliation_status=VALUES(reconciliation_status),notes=VALUES(notes),created_by=VALUES(created_by),created_at=NOW()';$status=(string)($_POST['reconciliation_status']??'Matched');$pdo->prepare($sql)->execute(['order'=>$orderId,'payment'=>$view,'status'=>$status,'notes'=>trim((string)($_POST['notes']??''))?:null,'admin'=>(int)(admin_user()['id']??0)?:null]);admin_audit($pdo,'payment.reconcile','payment_transaction',(string)$view,'Updated payment reconciliation',['order_id'=>$orderId,'status'=>$status]);header('Location: payments.php?view='.$view.'&saved=1');exit;}catch(Throwable $e){$error=$e instanceof RuntimeException?$e->getMessage():'Payment reconciliation could not be saved.';}}
}
$transactions=[];$transaction=null;if($ready){$transactions=$pdo->query("SELECT p.*,o.order_number,o.grand_total,o.currency,o.email,r.reconciliation_status,r.notes reconciliation_notes,r.created_at reconciled_at FROM payment_transactions p JOIN sales_orders o ON o.id=p.order_id LEFT JOIN payment_reconciliations r ON r.payment_transaction_id=p.id ORDER BY p.received_at DESC LIMIT 400")->fetchAll();if($view)foreach($transactions as $t)if((int)$t['id']===$view)$transaction=$t;}
?>
<div class="admin-heading"><div><div class="eyebrow">Finance</div><h1>Payment reconciliation</h1></div><a class="btn" href="refunds.php">Refunds</a></div><?php if(!$ready):?><div class="alert error">V7 payment reconciliation is not installed.</div><?php endif;?><?php if(isset($_GET['saved'])):?><div class="alert success">Reconciliation saved.</div><?php endif;?><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?>
<?php if($transaction):?><section class="card"><h2><?= e($transaction['order_number']) ?> · <?= e($transaction['gateway_payment_id']) ?></h2><p>Gateway status <strong><?= e($transaction['gateway_status']) ?></strong> · <?= e($transaction['currency']) ?> <?= number_format((float)$transaction['amount_gross'],2) ?></p><p>Validation: <?= $transaction['signature_valid']?'Signature ✓':'Signature ✗' ?> · <?= $transaction['source_valid']?'Source ✓':'Source ✗' ?> · <?= $transaction['amount_valid']?'Amount ✓':'Amount ✗' ?> · <?= $transaction['server_valid']?'Server ✓':'Server ✗' ?></p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="transaction_id" value="<?= (int)$transaction['id'] ?>"><div class="form-grid"><div class="field"><label>Reconciliation status</label><select name="reconciliation_status"><?php foreach(['Matched','Reviewed','Exception'] as $st):?><option<?= ($transaction['reconciliation_status']??'')===$st?' selected':'' ?>><?= e($st) ?></option><?php endforeach;?></select></div><div class="field full"><label>Notes</label><textarea name="notes"><?= e($transaction['reconciliation_notes']??'') ?></textarea></div></div><button class="btn primary">Save reconciliation</button></form></section><?php endif;?>
<?php if($ready):?><section class="card admin-section-gap"><h2>Gateway transactions</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Received</th><th>Order</th><th>Gateway</th><th>Amount</th><th>Validation</th><th>Reconciliation</th><th></th></tr></thead><tbody><?php foreach($transactions as $t):?><tr><td><?= e($t['received_at']) ?></td><td><a href="orders.php?view=<?= (int)$t['order_id'] ?>"><?= e($t['order_number']) ?></a><br><small><?= e($t['email']) ?></small></td><td><?= e($t['gateway_status']) ?><br><small><?= e($t['gateway_payment_id']) ?></small></td><td><?= e($t['currency']) ?> <?= number_format((float)$t['amount_gross'],2) ?></td><td><?= ($t['signature_valid']&&$t['source_valid']&&$t['amount_valid']&&$t['server_valid'])?'All checks passed':'Review required' ?></td><td><?= e($t['reconciliation_status']??'Unreconciled') ?></td><td><a href="payments.php?view=<?= (int)$t['id'] ?>">Open</a></td></tr><?php endforeach;?><?php if(!$transactions):?><tr><td colspan="7">No transactions recorded.</td></tr><?php endif;?></tbody></table></div></section><?php endif;?>
<?php require __DIR__.'/_footer.php';?>
