<?php
$adminTitle='Storefront';require __DIR__.'/_header.php';require_once __DIR__.'/../includes/commerce.php';require_once __DIR__.'/../includes/storefront.php';
$pdo=db();$ready=$pdo&&storefront_schema_ready($pdo);$error='';$message='';$productId=(int)($_GET['product']??$_POST['product_id']??0);
$products=$pdo?$pdo->query('SELECT id,sku,name,category,is_public FROM products ORDER BY sort_order,name')->fetchAll():[];
if(!$productId&&$products)$productId=(int)$products[0]['id'];
if($pdo&&$ready&&$_SERVER['REQUEST_METHOD']==='POST'){
    if(!csrf_valid($_POST['csrf_token']??null))$error='Your session expired.';else{try{
        $action=(string)($_POST['action']??'');
        if($action==='save_meta'){
            $stmt=$pdo->prepare('SELECT name FROM products WHERE id=:id');$stmt->execute(['id'=>$productId]);$name=(string)$stmt->fetchColumn();if($name==='')throw new RuntimeException('Product not found.');
            $slug=storefront_slugify((string)($_POST['slug']??''));if($slug==='')$slug=storefront_slugify($name);
            $sql='INSERT INTO product_storefront(product_id,slug,short_description,meta_title,meta_description,search_keywords,low_stock_threshold,stock_message,seo_indexable) VALUES(:product,:slug,:short,:title,:description,:keywords,:threshold,:stock,:indexable) ON DUPLICATE KEY UPDATE slug=VALUES(slug),short_description=VALUES(short_description),meta_title=VALUES(meta_title),meta_description=VALUES(meta_description),search_keywords=VALUES(search_keywords),low_stock_threshold=VALUES(low_stock_threshold),stock_message=VALUES(stock_message),seo_indexable=VALUES(seo_indexable)';
            $pdo->prepare($sql)->execute(['product'=>$productId,'slug'=>$slug,'short'=>trim((string)($_POST['short_description']??''))?:null,'title'=>trim((string)($_POST['meta_title']??''))?:null,'description'=>trim((string)($_POST['meta_description']??''))?:null,'keywords'=>trim((string)($_POST['search_keywords']??''))?:null,'threshold'=>max(0,(float)($_POST['low_stock_threshold']??5)),'stock'=>trim((string)($_POST['stock_message']??''))?:null,'indexable'=>isset($_POST['seo_indexable'])?1:0]);
            admin_audit($pdo,'storefront.meta.save','product',(string)$productId,'Updated storefront metadata',['slug'=>$slug]);$message='Storefront metadata saved.';
        }elseif($action==='save_variant'){
            $variantId=(int)($_POST['variant_id']??0);$sku=strtoupper(trim((string)($_POST['sku']??'')));$label=trim((string)($_POST['label']??''));$units=max(.001,(float)($_POST['units_per_sale']??1));$price=(float)($_POST['price']??0);$currency=strtoupper(trim((string)($_POST['currency']??commerce_currency())));$tax=max(0,(float)($_POST['tax_rate']??0));$min=max(.001,(float)($_POST['min_qty']??1));$max=trim((string)($_POST['max_qty']??''));$unitLabel=trim((string)($_POST['sale_unit_label']??'pack'))?:'pack';$sort=(int)($_POST['sort_order']??0);
            if(!preg_match('/^[A-Z0-9._-]{2,70}$/',$sku))throw new RuntimeException('Variant SKU must use 2–70 letters, numbers, dots, dashes or underscores.');if($label==='')throw new RuntimeException('Variant label is required.');if($price<=0)throw new RuntimeException('Variant price must be greater than zero.');
            $pdo->prepare("INSERT IGNORE INTO product_commerce(product_id,currency,cart_enabled) VALUES(:product,:currency,0)")->execute(['product'=>$productId,'currency'=>$currency]);
            if($variantId){$sql='UPDATE product_variants SET sku=:sku,label=:label,units_per_sale=:units,price=:price,currency=:currency,tax_rate=:tax,tax_inclusive=:inclusive,cart_enabled=:enabled,min_qty=:min,max_qty=:max,sale_unit_label=:unit_label,sort_order=:sort WHERE id=:id AND product_id=:product';$params=['id'=>$variantId,'product'=>$productId];}
            else{$sql='INSERT INTO product_variants(product_id,sku,label,units_per_sale,price,currency,tax_rate,tax_inclusive,cart_enabled,min_qty,max_qty,sale_unit_label,sort_order) VALUES(:product,:sku,:label,:units,:price,:currency,:tax,:inclusive,:enabled,:min,:max,:unit_label,:sort)';$params=['product'=>$productId];}
            $params+=['sku'=>$sku,'label'=>$label,'units'=>$units,'price'=>$price,'currency'=>$currency,'tax'=>$tax,'inclusive'=>isset($_POST['tax_inclusive'])?1:0,'enabled'=>isset($_POST['cart_enabled'])?1:0,'min'=>$min,'max'=>$max===''?null:max($min,(float)$max),'unit_label'=>$unitLabel,'sort'=>$sort];$pdo->prepare($sql)->execute($params);
            admin_audit($pdo,$variantId?'storefront.variant.update':'storefront.variant.create','product_variant',$variantId?(string)$variantId:(string)$pdo->lastInsertId(),'Updated sellable pack size',['product_id'=>$productId,'sku'=>$sku]);$message='Pack size saved.';
        }elseif($action==='disable_variant'){
            $variantId=(int)($_POST['variant_id']??0);$pdo->prepare('UPDATE product_variants SET cart_enabled=0 WHERE id=:id AND product_id=:product')->execute(['id'=>$variantId,'product'=>$productId]);admin_audit($pdo,'storefront.variant.disable','product_variant',(string)$variantId,'Disabled pack size',['product_id'=>$productId]);$message='Pack size disabled.';
        }elseif($action==='save_related'){
            $ids=array_values(array_unique(array_filter(array_map('intval',(array)($_POST['related']??[])),fn($id)=>$id>0&&$id!==$productId)));$pdo->beginTransaction();$pdo->prepare('DELETE FROM product_related_products WHERE product_id=:id')->execute(['id'=>$productId]);$stmt=$pdo->prepare('INSERT INTO product_related_products(product_id,related_product_id,sort_order) VALUES(:product,:related,:sort)');foreach($ids as $idx=>$related)$stmt->execute(['product'=>$productId,'related'=>$related,'sort'=>$idx]);$pdo->commit();admin_audit($pdo,'storefront.related.save','product',(string)$productId,'Updated related materials',['related_ids'=>$ids]);$message='Related materials saved.';
        }
    }catch(Throwable $e){if($pdo&&$pdo->inTransaction())$pdo->rollBack();$error=$e instanceof RuntimeException?$e->getMessage():'Storefront settings could not be saved.';}}
}
$selected=null;$meta=[];$variants=[];$relatedIds=[];
if($pdo&&$productId){$s=$pdo->prepare('SELECT p.*,pc.price base_price,pc.cart_enabled base_cart_enabled FROM products p LEFT JOIN product_commerce pc ON pc.product_id=p.id WHERE p.id=:id');$s->execute(['id'=>$productId]);$selected=$s->fetch()?:null;if($ready&&$selected){$meta=storefront_meta($pdo,$productId);$variants=storefront_variants($pdo,$productId,false);$s=$pdo->prepare('SELECT related_product_id FROM product_related_products WHERE product_id=:id');$s->execute(['id'=>$productId]);$relatedIds=array_map('intval',array_column($s->fetchAll(),'related_product_id'));}}
?>
<div class="admin-heading"><div><div class="eyebrow">Merchandising</div><h1>Storefront</h1></div><a class="btn" href="../catalog.php" target="_blank" rel="noopener">View catalogue</a></div>
<?php if(!$ready):?><div class="alert error">V8 storefront hardening is not installed. <a href="system.php">Run the V8 upgrade</a>.</div><?php endif;?><?php if($message):?><div class="alert success"><?= e($message) ?></div><?php endif;?><?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?>
<section class="card"><form method="get" class="inline-select"><label>Product</label><select name="product" onchange="this.form.submit()"><?php foreach($products as $p):?><option value="<?= (int)$p['id'] ?>"<?= (int)$p['id']===$productId?' selected':'' ?>><?= e($p['sku'].' · '.$p['name']) ?></option><?php endforeach;?></select><noscript><button class="btn">Open</button></noscript></form></section>
<?php if($ready&&$selected):?>
<div class="grid-2 admin-section-gap"><section class="card"><h2>Search &amp; SEO</h2><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save_meta"><input type="hidden" name="product_id" value="<?= $productId ?>"><div class="form-grid"><div class="field full"><label>URL slug</label><input name="slug" maxlength="160" value="<?= e($meta['slug']??storefront_slugify($selected['name'])) ?>"></div><div class="field full"><label>Short storefront description</label><textarea name="short_description" maxlength="500"><?= e($meta['short_description']??'') ?></textarea></div><div class="field full"><label>Meta title</label><input name="meta_title" maxlength="180" value="<?= e($meta['meta_title']??'') ?>"></div><div class="field full"><label>Meta description</label><textarea name="meta_description" maxlength="320"><?= e($meta['meta_description']??'') ?></textarea></div><div class="field full"><label>Search keywords</label><input name="search_keywords" maxlength="500" value="<?= e($meta['search_keywords']??'') ?>" placeholder="comma-separated internal search terms"></div><div class="field"><label>Low-stock threshold</label><input type="number" min="0" step="0.001" name="low_stock_threshold" value="<?= e((string)($meta['low_stock_threshold']??5)) ?>"></div><div class="field"><label>Custom stock message</label><input name="stock_message" maxlength="160" value="<?= e($meta['stock_message']??'') ?>" placeholder="Optional"></div><div class="field full admin-checks"><label><input type="checkbox" name="seo_indexable"<?= !isset($meta['seo_indexable'])||$meta['seo_indexable']?' checked':'' ?>> Allow search-engine indexing</label></div></div><button class="btn primary">Save storefront metadata</button></form></section>
<section class="card"><h2>Related materials</h2><p class="muted">Choose products to surface below this product page.</p><form method="post"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save_related"><input type="hidden" name="product_id" value="<?= $productId ?>"><div class="related-admin-list"><?php foreach($products as $p):if((int)$p['id']===$productId)continue;?><label><input type="checkbox" name="related[]" value="<?= (int)$p['id'] ?>"<?= in_array((int)$p['id'],$relatedIds,true)?' checked':'' ?>> <?= e($p['sku'].' · '.$p['name']) ?></label><?php endforeach;?></div><button class="btn">Save related materials</button></form></section></div>
<section class="card admin-section-gap"><div class="section-heading"><div><h2>Pack sizes / sellable variants</h2><p class="muted">Each sold pack reserves <code>units per sale</code> from the product's released batch inventory. Example: one 5-pack reserves five inventory units.</p></div></div>
<div class="commerce-product-list"><?php foreach($variants as $v):?><details class="commerce-product"><summary><strong><?= e($v['sku'].' · '.$v['label']) ?></strong><span><?= $v['cart_enabled']?'Enabled':'Disabled' ?> · <?= e($v['currency']) ?> <?= number_format((float)$v['price'],2) ?> · <?= e((string)$v['units_per_sale']) ?> units/<?= e($v['sale_unit_label']) ?></span></summary><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save_variant"><input type="hidden" name="product_id" value="<?= $productId ?>"><input type="hidden" name="variant_id" value="<?= (int)$v['id'] ?>"><div class="field"><label>Variant SKU</label><input name="sku" value="<?= e($v['sku']) ?>" required></div><div class="field"><label>Label</label><input name="label" value="<?= e($v['label']) ?>" required></div><div class="field"><label>Units per sale</label><input type="number" min="0.001" step="0.001" name="units_per_sale" value="<?= e((string)$v['units_per_sale']) ?>"></div><div class="field"><label>Price</label><input type="number" min="0.01" step="0.01" name="price" value="<?= e((string)$v['price']) ?>"></div><div class="field"><label>Currency</label><input name="currency" maxlength="3" value="<?= e($v['currency']) ?>"></div><div class="field"><label>Tax rate %</label><input type="number" min="0" step="0.001" name="tax_rate" value="<?= e((string)$v['tax_rate']) ?>"></div><div class="field"><label>Minimum qty</label><input type="number" min="0.001" step="0.001" name="min_qty" value="<?= e((string)$v['min_qty']) ?>"></div><div class="field"><label>Maximum qty</label><input type="number" min="0.001" step="0.001" name="max_qty" value="<?= e((string)($v['max_qty']??'')) ?>"></div><div class="field"><label>Sale unit label</label><input name="sale_unit_label" value="<?= e($v['sale_unit_label']) ?>"></div><div class="field"><label>Sort order</label><input type="number" name="sort_order" value="<?= (int)$v['sort_order'] ?>"></div><div class="field admin-checks"><label><input type="checkbox" name="tax_inclusive"<?= $v['tax_inclusive']?' checked':'' ?>> Price includes tax</label><label><input type="checkbox" name="cart_enabled"<?= $v['cart_enabled']?' checked':'' ?>> Cart enabled</label></div><div class="field full"><button class="btn">Save pack</button></div></form><form method="post" class="variant-disable-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="disable_variant"><input type="hidden" name="product_id" value="<?= $productId ?>"><input type="hidden" name="variant_id" value="<?= (int)$v['id'] ?>"><button class="link-button" type="submit">Disable pack</button></form></details><?php endforeach;?></div>
<details class="commerce-product admin-section-gap"<?= !$variants?' open':'' ?>><summary><strong>Add pack size</strong><span>Create a sellable variant</span></summary><form method="post" class="form-grid"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="save_variant"><input type="hidden" name="product_id" value="<?= $productId ?>"><div class="field"><label>Variant SKU</label><input name="sku" required placeholder="<?= e($selected['sku']) ?>-1"></div><div class="field"><label>Label</label><input name="label" required placeholder="1 vial / 5-pack"></div><div class="field"><label>Units per sale</label><input type="number" min="0.001" step="0.001" name="units_per_sale" value="1"></div><div class="field"><label>Price</label><input type="number" min="0.01" step="0.01" name="price" required></div><div class="field"><label>Currency</label><input name="currency" maxlength="3" value="<?= e(commerce_currency()) ?>"></div><div class="field"><label>Tax rate %</label><input type="number" min="0" step="0.001" name="tax_rate" value="0"></div><div class="field"><label>Minimum qty</label><input type="number" min="0.001" step="0.001" name="min_qty" value="1"></div><div class="field"><label>Maximum qty</label><input type="number" min="0.001" step="0.001" name="max_qty"></div><div class="field"><label>Sale unit label</label><input name="sale_unit_label" value="pack"></div><div class="field"><label>Sort order</label><input type="number" name="sort_order" value="0"></div><div class="field admin-checks"><label><input type="checkbox" name="tax_inclusive" checked> Price includes tax</label><label><input type="checkbox" name="cart_enabled" checked> Cart enabled</label></div><div class="field full"><button class="btn primary">Add pack size</button></div></form></details>
</section>
<?php endif;?>
<?php require __DIR__.'/_footer.php';?>
